In [1]:
# Import the dependencies
import pandas as pd

In [2]:
# Store the CSV into a DataFrame
government_regulation_df = pd.read_csv("Resources_mk/OxCGRT_latest(Aug31,2020).csv")
covid_stats_df = pd.read_csv("Resources_mk/owid-covid-data(Aug31,2020).csv")

C:\Users\twin_\anaconda3\envs\PythonData\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (2,3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

### Inspect and Clean: government_regulation_df

In [3]:
# Review initial DataFrame
government_regulation_df.head()

,CountryName,CountryCode,RegionName,RegionCode,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,C3_Cancel public events,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,Aruba,ABW,NaN,NaN,20200101,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Aruba,ABW,NaN,NaN,20200102,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Aruba,ABW,NaN,NaN,20200103,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Aruba,ABW,NaN,NaN,20200104,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Aruba,ABW,NaN,NaN,20200105,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
# Review data types to ensure appropriateness
government_regulation_df.dtypes

CountryName                               object
CountryCode                               object
RegionName                                object
RegionCode                                object
Date                                       int64
C1_School closing                        float64
C1_Flag                                  float64
C2_Workplace closing                     float64
C2_Flag                                  float64
C3_Cancel public events                  float64
C3_Flag                                  float64
C4_Restrictions on gatherings            float64
C4_Flag                                  float64
C5_Close public transport                float64
C5_Flag                                  float64
C6_Stay at home requirements             float64
C6_Flag                                  float64
C7_Restrictions on internal movement     float64
C7_Flag                                  float64
C8_International travel controls         float64
E1_Income support                        float64
E1_Flag                                  float64
E2_Debt/contract relief                  float64
E3_Fiscal measures                       float64
E4_International support                 float64
H1_Public information campaigns          float64
H1_Flag                                  float64
H2_Testing policy                        float64
H3_Contact tracing                       float64
H4_Emergency investment in healthcare    float64
H5_Investment in vaccines                float64
M1_Wildcard                              float64
ConfirmedCases                           float64
ConfirmedDeaths                          float64
StringencyIndex                          float64
StringencyIndexForDisplay                float64
StringencyLegacyIndex                    float64
StringencyLegacyIndexForDisplay          float64
GovernmentResponseIndex                  float64
GovernmentResponseIndexForDisplay        float64
ContainmentHealthIndex                   float64
ContainmentHealthIndexForDisplay         float64
EconomicSupportIndex                     float64
EconomicSupportIndexForDisplay           float64
dtype: object

In [5]:
# Convert "Date" column to format datetime
government_regulation_df['Date_updated'] = pd.to_datetime(government_regulation_df['Date'].astype(str), format='%Y%m%d')

# Drop old "Date" column
government_regulation_df = government_regulation_df.drop(["Date"], axis=1)

# Rearrange columns
government_regulation_df = government_regulation_df[['Date_updated', 
                                                     'CountryName',
                                                     'CountryCode',
                                                     'RegionName',
                                                     'RegionCode',
                                                     'C1_School closing',
                                                     'C1_Flag',
                                                     'C2_Workplace closing',
                                                     'C2_Flag',
                                                     'C3_Cancel public events',
                                                     'C3_Flag',
                                                     'C4_Restrictions on gatherings',
                                                     'C4_Flag', 
                                                     'C5_Close public transport',
                                                     'C5_Flag',
                                                     'C6_Stay at home requirements',
                                                     'C6_Flag',
                                                     'C7_Restrictions on internal movement',
                                                     'C7_Flag',
                                                     'C8_International travel controls',
                                                     'E1_Income support',
                                                     'E1_Flag',
                                                     'E2_Debt/contract relief',
                                                     'E3_Fiscal measures',
                                                     'E4_International support',
                                                     'H1_Public information campaigns',
                                                     'H1_Flag', 
                                                     'H2_Testing policy',
                                                     'H3_Contact tracing',
                                                     'H4_Emergency investment in healthcare',
                                                     'H5_Investment in vaccines',
                                                     'M1_Wildcard',
                                                     'ConfirmedCases',
                                                     'ConfirmedDeaths',
                                                     'StringencyIndex',
                                                     'StringencyIndexForDisplay',
                                                     'StringencyLegacyIndex',
                                                     'StringencyLegacyIndexForDisplay',
                                                     'GovernmentResponseIndex',
                                                     'GovernmentResponseIndexForDisplay',
                                                     'ContainmentHealthIndex',
                                                     'ContainmentHealthIndexForDisplay',
                                                     'EconomicSupportIndex',
                                                     'EconomicSupportIndexForDisplay'
                                                    ]]

government_regulation_df.head()

,Date_updated,CountryName,CountryCode,RegionName,RegionCode,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,C3_Cancel public events,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,2020-01-01,Aruba,ABW,NaN,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2020-01-02,Aruba,ABW,NaN,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2020-01-03,Aruba,ABW,NaN,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2020-01-04,Aruba,ABW,NaN,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2020-01-05,Aruba,ABW,NaN,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
# Re-review data types to ensure appropriateness
government_regulation_df.dtypes

Date_updated                             datetime64[ns]
CountryName                                      object
CountryCode                                      object
RegionName                                       object
RegionCode                                       object
C1_School closing                               float64
C1_Flag                                         float64
C2_Workplace closing                            float64
C2_Flag                                         float64
C3_Cancel public events                         float64
C3_Flag                                         float64
C4_Restrictions on gatherings                   float64
C4_Flag                                         float64
C5_Close public transport                       float64
C5_Flag                                         float64
C6_Stay at home requirements                    float64
C6_Flag                                         float64
C7_Restrictions on internal movement            float64
C7_Flag                                         float64
C8_International travel controls                float64
E1_Income support                               float64
E1_Flag                                         float64
E2_Debt/contract relief                         float64
E3_Fiscal measures                              float64
E4_International support                        float64
H1_Public information campaigns                 float64
H1_Flag                                         float64
H2_Testing policy                               float64
H3_Contact tracing                              float64
H4_Emergency investment in healthcare           float64
H5_Investment in vaccines                       float64
M1_Wildcard                                     float64
ConfirmedCases                                  float64
ConfirmedDeaths                                 float64
StringencyIndex                                 float64
StringencyIndexForDisplay                       float64
StringencyLegacyIndex                           float64
StringencyLegacyIndexForDisplay                 float64
GovernmentResponseIndex                         float64
GovernmentResponseIndexForDisplay               float64
ContainmentHealthIndex                          float64
ContainmentHealthIndexForDisplay                float64
EconomicSupportIndex                            float64
EconomicSupportIndexForDisplay                  float64
dtype: object

In [7]:
# Ensure completeness
government_regulation_df.count()

Date_updated                             58804
CountryName                              58804
CountryCode                              58804
RegionName                               13664
RegionCode                               13664
C1_School closing                        57121
C1_Flag                                  36208
C2_Workplace closing                     57007
C2_Flag                                  33923
C3_Cancel public events                  57084
C3_Flag                                  37034
C4_Restrictions on gatherings            57051
C4_Flag                                  34034
C5_Close public transport                57209
C5_Flag                                  21786
C6_Stay at home requirements             57051
C6_Flag                                  30527
C7_Restrictions on internal movement     57163
C7_Flag                                  30043
C8_International travel controls         57053
E1_Income support                        56111
E1_Flag                                  28100
E2_Debt/contract relief                  55682
E3_Fiscal measures                       46504
E4_International support                 46698
H1_Public information campaigns          56599
H1_Flag                                  45838
H2_Testing policy                        56255
H3_Contact tracing                       56216
H4_Emergency investment in healthcare    46008
H5_Investment in vaccines                46411
M1_Wildcard                                  0
ConfirmedCases                           46187
ConfirmedDeaths                          46187
StringencyIndex                          56948
StringencyIndexForDisplay                57740
StringencyLegacyIndex                    56988
StringencyLegacyIndexForDisplay          57780
GovernmentResponseIndex                  55972
GovernmentResponseIndexForDisplay        56763
ContainmentHealthIndex                   56209
ContainmentHealthIndexForDisplay         57000
EconomicSupportIndex                     55570
EconomicSupportIndexForDisplay           56313
dtype: int64

In [8]:
# Drop "M1_Wildcard" column as there is no useable data
government_regulation_df = government_regulation_df.drop(["M1_Wildcard"], axis=1)

government_regulation_df.count()

Date_updated                             58804
CountryName                              58804
CountryCode                              58804
RegionName                               13664
RegionCode                               13664
C1_School closing                        57121
C1_Flag                                  36208
C2_Workplace closing                     57007
C2_Flag                                  33923
C3_Cancel public events                  57084
C3_Flag                                  37034
C4_Restrictions on gatherings            57051
C4_Flag                                  34034
C5_Close public transport                57209
C5_Flag                                  21786
C6_Stay at home requirements             57051
C6_Flag                                  30527
C7_Restrictions on internal movement     57163
C7_Flag                                  30043
C8_International travel controls         57053
E1_Income support                        56111
E1_Flag                                  28100
E2_Debt/contract relief                  55682
E3_Fiscal measures                       46504
E4_International support                 46698
H1_Public information campaigns          56599
H1_Flag                                  45838
H2_Testing policy                        56255
H3_Contact tracing                       56216
H4_Emergency investment in healthcare    46008
H5_Investment in vaccines                46411
ConfirmedCases                           46187
ConfirmedDeaths                          46187
StringencyIndex                          56948
StringencyIndexForDisplay                57740
StringencyLegacyIndex                    56988
StringencyLegacyIndexForDisplay          57780
GovernmentResponseIndex                  55972
GovernmentResponseIndexForDisplay        56763
ContainmentHealthIndex                   56209
ContainmentHealthIndexForDisplay         57000
EconomicSupportIndex                     55570
EconomicSupportIndexForDisplay           56313
dtype: int64

In [9]:
# Drop columns deemed redundant/not useful 
government_regulation_df = government_regulation_df.drop(['C1_School closing', 
                                                          'C1_Flag', 
                                                          'C2_Workplace closing',
                                                          'C2_Flag', 
                                                          'C3_Cancel public events', 
                                                          'C3_Flag', 
                                                          'C4_Restrictions on gatherings', 
                                                          'C4_Flag', 
                                                          'C5_Close public transport',
                                                          'C5_Flag', 
                                                          'C6_Stay at home requirements', 
                                                          'C6_Flag', 
                                                          'C7_Restrictions on internal movement', 
                                                          'C7_Flag', 
                                                          'C8_International travel controls',
                                                          'E1_Income support',
                                                          'E1_Flag',
                                                          'E2_Debt/contract relief',
                                                          'E3_Fiscal measures',
                                                          'E4_International support',
                                                          'H1_Public information campaigns',
                                                          'H1_Flag', 
                                                          'H2_Testing policy', 
                                                          'H3_Contact tracing', 
                                                          'H4_Emergency investment in healthcare', 
                                                          'H5_Investment in vaccines', 
                                                          'ConfirmedCases', 
                                                          'ConfirmedDeaths', 
                                                          'StringencyIndexForDisplay', 
                                                          'StringencyLegacyIndexForDisplay', 
                                                          'GovernmentResponseIndexForDisplay',
                                                          'ContainmentHealthIndexForDisplay',
                                                          'EconomicSupportIndexForDisplay'
                                                         ], axis=1)

government_regulation_df

,Date_updated,CountryName,CountryCode,RegionName,RegionCode,StringencyIndex,StringencyLegacyIndex,GovernmentResponseIndex,ContainmentHealthIndex,EconomicSupportIndex
0,2020-01-01,Aruba,ABW,NaN,NaN,0.0,0.0,0.0,0.0,0.0
1,2020-01-02,Aruba,ABW,NaN,NaN,0.0,0.0,0.0,0.0,0.0
2,2020-01-03,Aruba,ABW,NaN,NaN,0.0,0.0,0.0,0.0,0.0
3,2020-01-04,Aruba,ABW,NaN,NaN,0.0,0.0,0.0,0.0,0.0
4,2020-01-05,Aruba,ABW,NaN,NaN,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
58799,2020-08-27,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58800,2020-08-28,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58801,2020-08-29,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58802,2020-08-30,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58803,2020-08-31,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
government_regulation_df

,Date_updated,CountryName,CountryCode,RegionName,RegionCode,StringencyIndex,StringencyLegacyIndex,GovernmentResponseIndex,ContainmentHealthIndex,EconomicSupportIndex
0,2020-01-01,Aruba,ABW,NaN,NaN,0.0,0.0,0.0,0.0,0.0
1,2020-01-02,Aruba,ABW,NaN,NaN,0.0,0.0,0.0,0.0,0.0
2,2020-01-03,Aruba,ABW,NaN,NaN,0.0,0.0,0.0,0.0,0.0
3,2020-01-04,Aruba,ABW,NaN,NaN,0.0,0.0,0.0,0.0,0.0
4,2020-01-05,Aruba,ABW,NaN,NaN,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
58799,2020-08-27,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58800,2020-08-28,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58801,2020-08-29,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58802,2020-08-30,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58803,2020-08-31,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Drop rows based on countries not included in "covid_stats_df"
index_drop_codes = government_regulation_df[(government_regulation_df["CountryCode"] == "MAC") |
                                            (government_regulation_df["CountryCode"] == "PCN") |
                                            (government_regulation_df["CountryCode"] == "RKS") |
                                            (government_regulation_df["CountryCode"] == "SLB") |
                                            (government_regulation_df["CountryCode"] == "TKM") |
                                            (government_regulation_df["CountryCode"] == "VUT")                                      
                                           ].index

government_regulation_df.drop(index_drop_codes, inplace=True)

government_regulation_df.head(10)

,Date_updated,CountryName,CountryCode,RegionName,RegionCode,StringencyIndex,StringencyLegacyIndex,GovernmentResponseIndex,ContainmentHealthIndex,EconomicSupportIndex
0,2020-01-01,Aruba,ABW,NaN,NaN,0.0,0.0,0.0,0.0,0.0
1,2020-01-02,Aruba,ABW,NaN,NaN,0.0,0.0,0.0,0.0,0.0
2,2020-01-03,Aruba,ABW,NaN,NaN,0.0,0.0,0.0,0.0,0.0
3,2020-01-04,Aruba,ABW,NaN,NaN,0.0,0.0,0.0,0.0,0.0
4,2020-01-05,Aruba,ABW,NaN,NaN,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
58799,2020-08-27,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58800,2020-08-28,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58801,2020-08-29,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58802,2020-08-30,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58803,2020-08-31,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
government_regulation_df.tail(10)

,Date_updated,CountryName,CountryCode,RegionName,RegionCode,StringencyIndex,StringencyLegacyIndex,GovernmentResponseIndex,ContainmentHealthIndex,EconomicSupportIndex
58794,2020-08-22,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58795,2020-08-23,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58796,2020-08-24,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58797,2020-08-25,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58798,2020-08-26,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58799,2020-08-27,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58800,2020-08-28,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58801,2020-08-29,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58802,2020-08-30,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58803,2020-08-31,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Inspect and Clean: covid_stats_df

In [12]:
# Review initial DataFrame
covid_stats_df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy
0,ABW,North America,Aruba,2020-03-13,2.0,2.0,NaN,0.0,0.0,NaN,...,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29
1,ABW,North America,Aruba,2020-03-19,NaN,NaN,0.286,NaN,NaN,0.0,...,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29
2,ABW,North America,Aruba,2020-03-20,4.0,2.0,0.286,0.0,0.0,0.0,...,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29
3,ABW,North America,Aruba,2020-03-21,NaN,NaN,0.286,NaN,NaN,0.0,...,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29
4,ABW,North America,Aruba,2020-03-22,NaN,NaN,0.286,NaN,NaN,0.0,...,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29

In [13]:
# Review data types to ensure appropriateness
covid_stats_df.dtypes

iso_code                            object
continent                           object
location                            object
date                                object
total_cases                        float64
new_cases                          float64
new_cases_smoothed                 float64
total_deaths                       float64
new_deaths                         float64
new_deaths_smoothed                float64
total_cases_per_million            float64
new_cases_per_million              float64
new_cases_smoothed_per_million     float64
total_deaths_per_million           float64
new_deaths_per_million             float64
new_deaths_smoothed_per_million    float64
new_tests                          float64
total_tests                        float64
total_tests_per_thousand           float64
new_tests_per_thousand             float64
new_tests_smoothed                 float64
new_tests_smoothed_per_thousand    float64
tests_per_case                     float64
positive_rate                      float64
tests_units                         object
stringency_index                   float64
population                         float64
population_density                 float64
median_age                         float64
aged_65_older                      float64
aged_70_older                      float64
gdp_per_capita                     float64
extreme_poverty                    float64
cardiovasc_death_rate              float64
diabetes_prevalence                float64
female_smokers                     float64
male_smokers                       float64
handwashing_facilities             float64
hospital_beds_per_thousand         float64
life_expectancy                    float64
dtype: object

In [14]:
# Change "date" format by removing "-"
covid_stats_df['date'] = covid_stats_df['date'].str.replace('-','')

# Convert "date" column to format datetime
covid_stats_df['date_updated'] = pd.to_datetime(covid_stats_df['date'].astype(str), format='%Y%m%d')

# Drop old "date" column
covid_stats_df = covid_stats_df.drop(["date"], axis=1)

# Rearrange columns
covid_stats_df = covid_stats_df[['date_updated', 
                                 'iso_code',
                                 'continent',
                                 'location',
                                 'total_cases',
                                 'new_cases',
                                 'new_cases_smoothed',
                                 'total_deaths',
                                 'new_deaths',
                                 'new_deaths_smoothed',
                                 'total_cases_per_million',
                                 'new_cases_per_million',
                                 'new_cases_smoothed_per_million',
                                 'total_deaths_per_million',
                                 'new_deaths_per_million',
                                 'new_deaths_smoothed_per_million',
                                 'new_tests',
                                 'total_tests',
                                 'total_tests_per_thousand',
                                 'new_tests_per_thousand',
                                 'new_tests_smoothed',
                                 'new_tests_smoothed_per_thousand',
                                 'tests_per_case',
                                 'positive_rate',
                                 'tests_units',
                                 'stringency_index',
                                 'population',
                                 'population_density',
                                 'median_age',
                                 'aged_65_older',
                                 'aged_70_older',
                                 'gdp_per_capita',
                                 'extreme_poverty',
                                 'cardiovasc_death_rate',
                                 'diabetes_prevalence',
                                 'female_smokers',
                                 'male_smokers',
                                 'handwashing_facilities',
                                 'hospital_beds_per_thousand',
                                 'life_expectancy'
                                ]]
covid_stats_df.head()

,date_updated,iso_code,continent,location,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy
0,2020-03-13,ABW,North America,Aruba,2.0,2.0,NaN,0.0,0.0,NaN,...,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29
1,2020-03-19,ABW,North America,Aruba,NaN,NaN,0.286,NaN,NaN,0.0,...,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29
2,2020-03-20,ABW,North America,Aruba,4.0,2.0,0.286,0.0,0.0,0.0,...,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29
3,2020-03-21,ABW,North America,Aruba,NaN,NaN,0.286,NaN,NaN,0.0,...,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29
4,2020-03-22,ABW,North America,Aruba,NaN,NaN,0.286,NaN,NaN,0.0,...,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29

In [15]:
# Re-review data types to ensure appropriateness
covid_stats_df.dtypes

date_updated                       datetime64[ns]
iso_code                                   object
continent                                  object
location                                   object
total_cases                               float64
new_cases                                 float64
new_cases_smoothed                        float64
total_deaths                              float64
new_deaths                                float64
new_deaths_smoothed                       float64
total_cases_per_million                   float64
new_cases_per_million                     float64
new_cases_smoothed_per_million            float64
total_deaths_per_million                  float64
new_deaths_per_million                    float64
new_deaths_smoothed_per_million           float64
new_tests                                 float64
total_tests                               float64
total_tests_per_thousand                  float64
new_tests_per_thousand                    float64
new_tests_smoothed                        float64
new_tests_smoothed_per_thousand           float64
tests_per_case                            float64
positive_rate                             float64
tests_units                                object
stringency_index                          float64
population                                float64
population_density                        float64
median_age                                float64
aged_65_older                             float64
aged_70_older                             float64
gdp_per_capita                            float64
extreme_poverty                           float64
cardiovasc_death_rate                     float64
diabetes_prevalence                       float64
female_smokers                            float64
male_smokers                              float64
handwashing_facilities                    float64
hospital_beds_per_thousand                float64
life_expectancy                           float64
dtype: object

In [16]:
# Ensure completeness
covid_stats_df.count()

date_updated                       40748
iso_code                           40503
continent                          40258
location                           40748
total_cases                        40173
new_cases                          39992
new_cases_smoothed                 39210
total_deaths                       40173
new_deaths                         39992
new_deaths_smoothed                39210
total_cases_per_million            39928
new_cases_per_million              39928
new_cases_smoothed_per_million     39145
total_deaths_per_million           39928
new_deaths_per_million             39928
new_deaths_smoothed_per_million    39145
new_tests                          13112
total_tests                        13443
total_tests_per_thousand           13443
new_tests_per_thousand             13112
new_tests_smoothed                 14742
new_tests_smoothed_per_thousand    14742
tests_per_case                     13630
positive_rate                      13986
tests_units                        15497
stringency_index                   33598
population                         40503
population_density                 38693
median_age                         36390
aged_65_older                      35855
aged_70_older                      36202
gdp_per_capita                     35937
extreme_poverty                    23999
cardiovasc_death_rate              36403
diabetes_prevalence                37671
female_smokers                     28670
male_smokers                       28313
handwashing_facilities             16905
hospital_beds_per_thousand         32974
life_expectancy                    40002
dtype: int64

In [18]:
# Drop columns deemed redundant/not useful 
covid_stats_df = covid_stats_df.drop(['new_cases_smoothed', 
                                      'new_deaths_smoothed',
                                      'total_cases_per_million',
                                      'new_cases_per_million',
                                      'new_cases_smoothed_per_million',
                                      'total_deaths_per_million',
                                      'new_deaths_per_million',
                                      'new_deaths_smoothed_per_million',
                                      'total_tests_per_thousand',
                                      'new_tests_per_thousand',
                                      'new_tests_smoothed',
                                      'new_tests_smoothed_per_thousand',
                                      'stringency_index',
                                      'population',
                                      'population_density',
                                      'median_age',
                                      'aged_65_older',
                                      'aged_70_older',
                                      'gdp_per_capita',
                                      'extreme_poverty',
                                      'cardiovasc_death_rate',
                                      'diabetes_prevalence',
                                      'female_smokers',
                                      'male_smokers',
                                      'handwashing_facilities',
                                      'hospital_beds_per_thousand',
                                      'life_expectancy'
                                     ], axis=1)

covid_stats_df

,date_updated,iso_code,continent,location,total_cases,new_cases,total_deaths,new_deaths,new_tests,total_tests,tests_per_case,positive_rate,tests_units
0,2020-03-13,ABW,North America,Aruba,2.0,2.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
1,2020-03-19,ABW,North America,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-03-20,ABW,North America,Aruba,4.0,2.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
3,2020-03-21,ABW,North America,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-03-22,ABW,North America,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40743,2020-08-27,NaN,NaN,International,696.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN
40744,2020-08-28,NaN,NaN,International,696.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN
40745,2020-08-29,NaN,NaN,International,696.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN
40746,2020-08-30,NaN,NaN,International,696.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN
40747,2020-08-31,NaN,NaN,International,696.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
# Drop rows based on countries not included in "government_regulation_df"
index_drop_codes = covid_stats_df[(covid_stats_df['iso_code'] == 'ARM') |
                                  (covid_stats_df['iso_code'] == 'ATG') |
                                  (covid_stats_df['iso_code'] == 'BES') |
                                  (covid_stats_df['iso_code'] == 'BHS') |
                                  (covid_stats_df['iso_code'] == 'COM') |
                                  (covid_stats_df['iso_code'] == 'CUW') |
                                  (covid_stats_df['iso_code'] == 'ESH') |
                                  (covid_stats_df['iso_code'] == 'FRO') | 
                                  (covid_stats_df['iso_code'] == 'GGY') |
                                  (covid_stats_df['iso_code'] == 'GNB') |
                                  (covid_stats_df['iso_code'] == 'GNQ') |
                                  (covid_stats_df['iso_code'] == 'GRD') |
                                  (covid_stats_df['iso_code'] == 'IMN') |
                                  (covid_stats_df['iso_code'] == 'JEY') |
                                  (covid_stats_df['iso_code'] == 'KNA') |
                                  (covid_stats_df['iso_code'] == 'LCA') |
                                  (covid_stats_df['iso_code'] == 'LIE') |
                                  (covid_stats_df['iso_code'] == 'MCO') |
                                  (covid_stats_df['iso_code'] == 'MDV') |
                                  (covid_stats_df['iso_code'] == 'MKD') |
                                  (covid_stats_df['iso_code'] == 'MLT') |
                                  (covid_stats_df['iso_code'] == 'MNE') |
                                  (covid_stats_df['iso_code'] == 'MNP') |
                                  (covid_stats_df['iso_code'] == 'NCL') |
                                  (covid_stats_df['iso_code'] == 'OWID_KOS') |
                                  (covid_stats_df['iso_code'] == 'OWID_WRL') |
                                  (covid_stats_df['iso_code'] == 'PYF') |
                                  (covid_stats_df['iso_code'] == 'STP') |
                                  (covid_stats_df['iso_code'] == 'SXM') |
                                  (covid_stats_df['iso_code'] == 'VAT') |
                                  (covid_stats_df['iso_code'] == 'VCT') |
                                  (covid_stats_df['iso_code'] == 'VIR') |
                                  (covid_stats_df['location'] == 'International')
                                 ].index

covid_stats_df.drop(index_drop_codes, inplace=True)

covid_stats_df

,date_updated,iso_code,continent,location,total_cases,new_cases,total_deaths,new_deaths,new_tests,total_tests,tests_per_case,positive_rate,tests_units
0,2020-03-13,ABW,North America,Aruba,2.0,2.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
1,2020-03-19,ABW,North America,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-03-20,ABW,North America,Aruba,4.0,2.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
3,2020-03-21,ABW,North America,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-03-22,ABW,North America,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40253,2020-08-27,ZWE,Africa,Zimbabwe,6251.0,55.0,179.0,13.0,951.0,95721.0,12.883,0.078,tests performed
40254,2020-08-28,ZWE,Africa,Zimbabwe,6292.0,41.0,189.0,10.0,1551.0,97272.0,13.846,0.072,tests performed
40255,2020-08-29,ZWE,Africa,Zimbabwe,6388.0,96.0,195.0,6.0,NaN,NaN,NaN,NaN,NaN
40256,2020-08-30,ZWE,Africa,Zimbabwe,6406.0,18.0,196.0,1.0,NaN,NaN,NaN,NaN,NaN
40257,2020-08-31,ZWE,Africa,Zimbabwe,6412.0,6.0,196.0,0.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
covid_stats_df

### Initial Analysis