# Modification of dataset to include all feature & target variables for analysis

In [1]:
# import dependencies
import pandas as pd
import numpy as np
from statistics import mean
from datetime import timedelta

In [2]:
# load files
govReg = pd.read_csv("OxCGRT_latest(Aug31,2020).csv")
gdp = pd.read_csv("owid-covid-data(Aug31,2020).csv")
mobil = pd.read_csv("regional_mobility.csv")

merged_covid = pd.read_csv("merged_covid_FINAL.csv")

string = pd.read_csv("stringency.csv")
health = pd.read_csv("health.csv")
econ = pd.read_csv("econ_support.csv")
avgMaxGovResp = pd.read_csv("gov_resp.csv")

/Users/patricialan/opt/anaconda3/envs/PythonData/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3062: DtypeWarning: Columns (2,3) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
# preview data
display(merged_covid)
display(avgMaxGovResp)
display(list(gdp.columns))

# find out number of countries in merged_covid: 164 countries
len(list(merged_covid['location'].unique()))

,primary_key_reaction,date_updated,iso_code,continent,location,population,population_density,median_age,new_cases,percentage_of_Pop_New_Cases,...,primary_key_response,StringencyIndex_updated,percentage_change_stringency,StringencyLegacyIndex_updated,GovernmentResponseIndex_updated,percentage_change_GovernmentResponse,ContainmentHealthIndex_updated,percentage_change_ContainmentHealth,EconomicSupportIndex_updated,percentage_change_EconomicSupport
0,ABW2020-03-13,2020-03-13,ABW,North America,Aruba,106766.0,584.800,41.2,2.0,0.001873,...,ABW2020-03-13,0.00,0.000000,0.00,2.56,0.000000,3.03,0.000000,0.0,0.0
1,ABW2020-03-19,2020-03-19,ABW,North America,Aruba,106766.0,584.800,41.2,0.0,0.000000,...,ABW2020-03-19,33.33,0.000000,42.86,29.49,15.015601,34.85,15.016502,0.0,0.0
2,ABW2020-03-20,2020-03-20,ABW,North America,Aruba,106766.0,584.800,41.2,2.0,0.001873,...,ABW2020-03-20,33.33,0.000000,42.86,29.49,0.000000,34.85,0.000000,0.0,0.0
3,ABW2020-03-21,2020-03-21,ABW,North America,Aruba,106766.0,584.800,41.2,0.0,0.000000,...,ABW2020-03-21,44.44,33.333333,60.71,37.18,26.076636,43.94,26.083214,0.0,0.0
4,ABW2020-03-22,2020-03-22,ABW,North America,Aruba,106766.0,584.800,41.2,0.0,0.000000,...,ABW2020-03-22,44.44,0.000000,60.71,37.18,0.000000,43.94,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32272,ZWE2020-08-27,2020-08-27,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,55.0,0.000370,...,ZWE2020-08-27,80.56,0.000000,88.10,66.03,0.000000,73.48,0.000000,25.0,0.0
32273,ZWE2020-08-28,2020-08-28,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,41.0,0.000276,...,ZWE2020-08-28,80.56,0.000000,88.10,66.03,0.000000,73.48,0.000000,25.0,0.0
32274,ZWE2020-08-29,2020-08-29,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,96.0,0.000646,...,ZWE2020-08-29,80.56,0.000000,88.10,66.03,0.000000,73.48,0.000000,25.0,0.0
32275,ZWE2020-08-30,2020-08-30,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,18.0,0.000121,...,ZWE2020-08-30,80.56,0.000000,88.10,66.03,0.000000,73.48,0.000000,25.0,0.0
32276,ZWE2020-08-31,2020-08-31,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,6.0,0.000040,...,ZWE2020-08-31,80.56,0.000000,88.10,66.03,0.000000,73.48,0.000000,25.0,0.0

        location  GovernmentResponseIndex_updated
0       Honduras                        86.684510
1      Argentina                        85.190196
2    El Salvador                        84.830980
3       Colombia                        84.497516
4          Nepal                        83.451307
..           ...                              ...
159        Yemen                        32.003750
160     Tanzania                        27.344510
161      Burundi                        26.477778
162      Belarus                        22.989020
163    Nicaragua                        12.116340

[164 rows x 2 columns]

['iso_code',
 'continent',
 'location',
 'date',
 'total_cases',
 'new_cases',
 'new_cases_smoothed',
 'total_deaths',
 'new_deaths',
 'new_deaths_smoothed',
 'total_cases_per_million',
 'new_cases_per_million',
 'new_cases_smoothed_per_million',
 'total_deaths_per_million',
 'new_deaths_per_million',
 'new_deaths_smoothed_per_million',
 'new_tests',
 'total_tests',
 'total_tests_per_thousand',
 'new_tests_per_thousand',
 'new_tests_smoothed',
 'new_tests_smoothed_per_thousand',
 'tests_per_case',
 'positive_rate',
 'tests_units',
 'stringency_index',
 'population',
 'population_density',
 'median_age',
 'aged_65_older',
 'aged_70_older',
 'gdp_per_capita',
 'extreme_poverty',
 'cardiovasc_death_rate',
 'diabetes_prevalence',
 'female_smokers',
 'male_smokers',
 'handwashing_facilities',
 'hospital_beds_per_thousand',
 'life_expectancy']

164

In [4]:
# sort by location, then date
merged_covid = merged_covid.sort_values(by=['location','date_updated'])
display(merged_covid)
display(merged_covid.describe())

# reset index
merged_covid = merged_covid.reset_index()
merged_covid.drop(columns=['index'], inplace=True)
merged_covid

,primary_key_reaction,date_updated,iso_code,continent,location,population,population_density,median_age,new_cases,percentage_of_Pop_New_Cases,...,primary_key_response,StringencyIndex_updated,percentage_change_stringency,StringencyLegacyIndex_updated,GovernmentResponseIndex_updated,percentage_change_GovernmentResponse,ContainmentHealthIndex_updated,percentage_change_ContainmentHealth,EconomicSupportIndex_updated,percentage_change_EconomicSupport
167,AFG2020-01-01,2020-01-01,AFG,Asia,Afghanistan,38928341.0,54.422,18.6,0.0,0.000000,...,AFG2020-01-01,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0
168,AFG2020-01-02,2020-01-02,AFG,Asia,Afghanistan,38928341.0,54.422,18.6,0.0,0.000000,...,AFG2020-01-02,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0
169,AFG2020-01-03,2020-01-03,AFG,Asia,Afghanistan,38928341.0,54.422,18.6,0.0,0.000000,...,AFG2020-01-03,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0
170,AFG2020-01-04,2020-01-04,AFG,Asia,Afghanistan,38928341.0,54.422,18.6,0.0,0.000000,...,AFG2020-01-04,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0
171,AFG2020-01-05,2020-01-05,AFG,Asia,Afghanistan,38928341.0,54.422,18.6,0.0,0.000000,...,AFG2020-01-05,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32272,ZWE2020-08-27,2020-08-27,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,55.0,0.000370,...,ZWE2020-08-27,80.56,0.0,88.1,66.03,0.0,73.48,0.0,25.0,0.0
32273,ZWE2020-08-28,2020-08-28,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,41.0,0.000276,...,ZWE2020-08-28,80.56,0.0,88.1,66.03,0.0,73.48,0.0,25.0,0.0
32274,ZWE2020-08-29,2020-08-29,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,96.0,0.000646,...,ZWE2020-08-29,80.56,0.0,88.1,66.03,0.0,73.48,0.0,25.0,0.0
32275,ZWE2020-08-30,2020-08-30,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,18.0,0.000121,...,ZWE2020-08-30,80.56,0.0,88.1,66.03,0.0,73.48,0.0,25.0,0.0
32276,ZWE2020-08-31,2020-08-31,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,6.0,0.000040,...,ZWE2020-08-31,80.56,0.0,88.1,66.03,0.0,73.48,0.0,25.0,0.0

,population,population_density,median_age,new_cases,percentage_of_Pop_New_Cases,new_deaths,percentage_of_Pop_New_Deaths,new_tests,percentage_of_Pop_New_Tests,total_cases_updated,...,percentage_of_Pop_Total_Tests,StringencyIndex_updated,percentage_change_stringency,StringencyLegacyIndex_updated,GovernmentResponseIndex_updated,percentage_change_GovernmentResponse,ContainmentHealthIndex_updated,percentage_change_ContainmentHealth,EconomicSupportIndex_updated,percentage_change_EconomicSupport
count,3.227700e+04,32277.000000,32277.000000,32277.000000,32277.000000,32277.000000,3.227700e+04,3.227700e+04,32277.000000,3.227700e+04,...,32277.000000,32277.000000,32277.000000,32277.000000,32277.000000,32277.000000,32277.000000,32277.000000,32277.000000,32277.000000
mean,5.400962e+07,214.197672,31.332131,778.920656,0.001991,26.154042,5.072572e-07,8.487867e+03,0.024842,4.745188e+04,...,1.928935,58.044062,1.308332,64.012734,55.398830,1.274466,58.043087,1.226407,40.854943,0.337230
std,1.764115e+08,728.593605,9.175007,4360.424882,0.005546,138.626066,2.001007e-06,5.284508e+04,0.074306,2.709722e+05,...,5.493011,28.321004,19.904059,28.648400,24.321508,13.818227,25.638560,14.416320,32.776192,7.614218
min,9.834000e+04,1.980000,15.100000,-2461.000000,-0.221254,-1918.000000,-6.790114e-05,-3.743000e+03,-0.039824,0.000000e+00,...,0.000000,0.000000,-100.000000,0.000000,0.000000,-59.979210,0.000000,-59.947183,0.000000,-100.000000
25%,4.822233e+06,32.333000,23.500000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,7.200000e+01,...,0.000000,39.810000,0.000000,50.000000,44.870000,0.000000,44.700000,0.000000,0.000000,0.000000
50%,1.132662e+07,82.805000,31.100000,18.000000,0.000182,0.000000,0.000000e+00,0.000000e+00,0.000000,1.331000e+03,...,0.000000,65.740000,0.000000,72.620000,62.180000,0.000000,65.150000,0.000000,50.000000,0.000000
75%,3.892834e+07,204.430000,39.800000,221.000000,0.001469,4.000000,2.433856e-07,1.911000e+03,0.013440,1.297400e+04,...,0.968671,80.560000,0.000000,85.710000,73.720000,0.000000,77.270000,0.000000,75.000000,0.000000
max,1.439324e+09,7915.731000,48.200000,78761.000000,0.189258,4928.000000,1.193442e-04,1.194086e+06,1.657412,5.997163e+06,...,70.895970,100.000000,1965.107914,100.000000,96.150000,655.459272,100.000000,655.425220,100.000000,400.000000

,primary_key_reaction,date_updated,iso_code,continent,location,population,population_density,median_age,new_cases,percentage_of_Pop_New_Cases,...,primary_key_response,StringencyIndex_updated,percentage_change_stringency,StringencyLegacyIndex_updated,GovernmentResponseIndex_updated,percentage_change_GovernmentResponse,ContainmentHealthIndex_updated,percentage_change_ContainmentHealth,EconomicSupportIndex_updated,percentage_change_EconomicSupport
0,AFG2020-01-01,2020-01-01,AFG,Asia,Afghanistan,38928341.0,54.422,18.6,0.0,0.000000,...,AFG2020-01-01,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0
1,AFG2020-01-02,2020-01-02,AFG,Asia,Afghanistan,38928341.0,54.422,18.6,0.0,0.000000,...,AFG2020-01-02,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0
2,AFG2020-01-03,2020-01-03,AFG,Asia,Afghanistan,38928341.0,54.422,18.6,0.0,0.000000,...,AFG2020-01-03,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0
3,AFG2020-01-04,2020-01-04,AFG,Asia,Afghanistan,38928341.0,54.422,18.6,0.0,0.000000,...,AFG2020-01-04,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0
4,AFG2020-01-05,2020-01-05,AFG,Asia,Afghanistan,38928341.0,54.422,18.6,0.0,0.000000,...,AFG2020-01-05,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32272,ZWE2020-08-27,2020-08-27,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,55.0,0.000370,...,ZWE2020-08-27,80.56,0.0,88.1,66.03,0.0,73.48,0.0,25.0,0.0
32273,ZWE2020-08-28,2020-08-28,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,41.0,0.000276,...,ZWE2020-08-28,80.56,0.0,88.1,66.03,0.0,73.48,0.0,25.0,0.0
32274,ZWE2020-08-29,2020-08-29,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,96.0,0.000646,...,ZWE2020-08-29,80.56,0.0,88.1,66.03,0.0,73.48,0.0,25.0,0.0
32275,ZWE2020-08-30,2020-08-30,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,18.0,0.000121,...,ZWE2020-08-30,80.56,0.0,88.1,66.03,0.0,73.48,0.0,25.0,0.0
32276,ZWE2020-08-31,2020-08-31,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,6.0,0.000040,...,ZWE2020-08-31,80.56,0.0,88.1,66.03,0.0,73.48,0.0,25.0,0.0

## Find avg. minimum government response for each country

In [5]:
# for loop to find avg. min. gov response
# avg. min. gov response is 14-15

countries = list(merged_covid['location'].unique())
# length of "countries" list
print(len(countries))

min_list = []

for country in countries:
    countryLoc = merged_covid.loc[merged_covid['location'] == country]
    govResp = countryLoc['GovernmentResponseIndex_updated']
    govResp_min = govResp.min(axis=0)
    min_list.append(govResp_min)

# view min. gov response of all countries
print(min_list)
# ensure obtained min. gov response for all countries (there should be 164)
print(len(min_list))

# avg. min. gov response
mean = mean(min_list)
mean

164
[0.0, 31.41, 0.0, 10.26, 7.69, 2.56, 0.0, 0.0, 0.0, 0.0, 16.03, 29.49, 0.0, 0.0, 41.67, 29.49, 32.05, 21.15, 18.59, 48.72, 0.0, 22.44, 17.31, 10.26, 14.1, 0.0, 3.85, 3.85, 32.69, 11.54, 25.64, 0.0, 6.41, 13.46, 11.54, 17.95, 11.54, 0.0, 18.59, 23.08, 0.0, 17.95, 0.0, 35.9, 0.0, 0.0, 0.0, 54.49, 15.38, 0.0, 8.33, 7.69, 0.0, 0.0, 28.21, 34.94, 0.0, 0.0, 13.46, 0.0, 41.03, 31.41, 18.59, 27.56, 26.28, 14.1, 44.23, 17.95, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 27.56, 0.0, 0.0, 16.03, 9.62, 0.0, 50.64, 20.51, 8.33, 0.0, 51.92, 27.56, 67.31, 0.0, 0.0, 53.21, 42.31, 0.0, 50.0, 19.23, 38.46, 0.0, 7.69, 44.23, 0.0, 41.03, 30.13, 16.03, 0.0, 0.0, 0.0, 8.33, 23.72, 0.0, 0.0, 0.0, 0.0, 57.69, 5.77, 23.08, 14.1, 2.56, 0.0, 7.69, 17.95, 63.46, 0.0, 0.0, 0.0, 33.65, 15.38, 0.0, 9.62, 30.13, 35.26, 0.0, 21.79, 20.51, 5.77, 1.92, 0.0, 7.69, 0.0, 36.54, 29.49, 23.72, 0.0, 0.0, 38.46, 15.38, 0.0, 22.44, 0.0, 24.36, 6.41, 25.0, 42.95, 10.26, 0.0, 0.0, 0.0, 35.26, 51.92, 38.46, 0.0, 21.79, 14.1, 19.23]
164

14.966463414634147

## Get date of max. value of gov response for each country

In [6]:
# for loop to get index of max. value of gov response
maxIndex_list = []

for country in countries:
    countryLoc = merged_covid.loc[merged_covid['location'] == country]
    govResp = countryLoc['GovernmentResponseIndex_updated']
    govResp_maxIndex = govResp.idxmax()
    maxIndex_list.append(govResp_maxIndex)
    
print(maxIndex_list)

# ensure got index for all countries
print(len(maxIndex_list))

[102, 322, 640, 682, 870, 1053, 1412, 1530, 1857, 2020, 2213, 2386, 2631, 2889, 3061, 3204, 3375, 3538, 3715, 3860, 4157, 4287, 4480, 4657, 4790, 5029, 5212, 5439, 5650, 5809, 5949, 6210, 6411, 6567, 6709, 6913, 7057, 7303, 7512, 7660, 7888, 8075, 8346, 8500, 8742, 8959, 9263, 9413, 9532, 9802, 10080, 10178, 10402, 10635, 10844, 11115, 11255, 11504, 11655, 11898, 12198, 12247, 12395, 12575, 12794, 12905, 13069, 13117, 13335, 13598, 13857, 14181, 14377, 14571, 14817, 15065, 15247, 15485, 15645, 15850, 16032, 16282, 16418, 16599, 16749, 17005, 17216, 17286, 17451, 17688, 17908, 18091, 18367, 18534, 18671, 18859, 18976, 19225, 19424, 19600, 19834, 20012, 20125, 20284, 20510, 20755, 21000, 21180, 21344, 21596, 21818, 22177, 22336, 22504, 22689, 22839, 23010, 23218, 23444, 23619, 23804, 23982, 24310, 24467, 24714, 24843, 25089, 25226, 25403, 25582, 25759, 26026, 26155, 26325, 26505, 26760, 26951, 27194, 27439, 27662, 27833, 27941, 28247, 28467, 28630, 28729, 28992, 29141, 29361, 29505, 29691, 29844, 29987, 30201, 30421, 30721, 30892, 31068, 31263, 31488, 31658, 31824, 31991, 32132]
164

In [7]:
# for loop to get max. value of gov response
maxValue_list = []

for country in countries:
    countryLoc = merged_covid.loc[merged_covid['location'] == country]
    govResp = countryLoc['GovernmentResponseIndex_updated']
    govResp_maxValue = govResp.max()
    maxValue_list.append(govResp_maxValue)
    
print(maxValue_list)

# ensure got max. value for all countries
print(len(maxValue_list))

[64.74, 81.41, 78.85, 75.64, 91.03, 81.41, 81.73, 85.26, 87.18, 83.33, 85.26, 80.13, 25.0, 78.85, 73.08, 61.86, 82.05, 76.92, 75.0, 75.64, 68.91, 51.28, 74.36, 72.44, 33.33, 53.85, 58.33, 74.68, 81.73, 62.82, 75.64, 86.22, 77.88, 87.18, 85.26, 74.36, 68.59, 92.95, 87.18, 96.15, 85.26, 69.87, 74.36, 88.46, 80.13, 87.82, 82.69, 92.31, 75.0, 64.74, 73.08, 88.46, 55.77, 82.69, 85.26, 66.67, 87.82, 74.36, 82.69, 71.15, 72.44, 83.33, 63.46, 74.36, 65.38, 89.1, 76.92, 76.92, 67.95, 96.15, 65.71, 66.99, 80.77, 84.62, 91.03, 85.26, 74.36, 50.64, 83.97, 83.01, 80.77, 87.82, 77.88, 86.54, 65.38, 69.23, 63.46, 67.31, 75.64, 84.62, 80.77, 72.44, 67.31, 78.85, 66.03, 71.79, 71.15, 63.46, 76.92, 80.77, 85.26, 66.03, 70.51, 72.44, 88.46, 71.15, 89.1, 14.1, 52.56, 69.55, 75.0, 91.67, 82.69, 80.77, 83.33, 78.53, 85.9, 87.18, 91.67, 66.03, 83.97, 86.54, 80.77, 82.69, 83.97, 82.05, 88.46, 76.28, 85.26, 81.41, 82.05, 84.62, 83.97, 86.54, 44.23, 85.26, 80.13, 81.41, 82.05, 80.13, 78.85, 76.28, 50.64, 67.95, 64.74, 38.46, 81.41, 74.36, 68.59, 87.18, 82.05, 76.28, 78.85, 80.13, 85.26, 78.85, 71.47, 66.03, 84.62, 75.64, 85.9, 40.38, 63.14, 71.15]
164

In [8]:
# for loop to get date of first max. gov. response
dateMax_list = []

for index in maxIndex_list:
    dateMax = merged_covid.iloc[index,1]
    dateMax_list.append(dateMax)

dateMax_list

['2020-04-12',
 '2020-05-26',
 '2020-08-08',
 '2020-04-09',
 '2020-03-25',
 '2020-04-10',
 '2020-08-03',
 '2020-03-30',
 '2020-06-21',
 '2020-04-01',
 '2020-04-13',
 '2020-04-19',
 '2020-04-20',
 '2020-05-04',
 '2020-05-15',
 '2020-04-20',
 '2020-04-17',
 '2020-04-07',
 '2020-04-10',
 '2020-04-02',
 '2020-05-25',
 '2020-04-11',
 '2020-04-29',
 '2020-05-04',
 '2020-04-14',
 '2020-04-09',
 '2020-04-18',
 '2020-04-01',
 '2020-05-18',
 '2020-05-08',
 '2020-04-13',
 '2020-07-03',
 '2020-05-21',
 '2020-04-27',
 '2020-03-31',
 '2020-04-27',
 '2020-03-31',
 '2020-04-02',
 '2020-05-11',
 '2020-04-16',
 '2020-03-31',
 '2020-04-15',
 '2020-05-12',
 '2020-04-30',
 '2020-04-28',
 '2020-04-01',
 '2020-05-31',
 '2020-05-15',
 '2020-04-01',
 '2020-04-27',
 '2020-08-12',
 '2020-04-17',
 '2020-03-28',
 '2020-03-17',
 '2020-04-24',
 '2020-08-06',
 '2020-04-24',
 '2020-04-29',
 '2020-04-09',
 '2020-04-08',
 '2020-08-20',
 '2020-04-21',
 '2020-03-30',
 '2020-04-09',
 '2020-06-02',
 '2020-04-03',
 '2020-08-07',
 '2020-04-16',
 '2020-03-21',
 '2020-04-09',
 '2020-04-24',
 '2020-07-13',
 '2020-05-26',
 '2020-04-06',
 '2020-04-08',
 '2020-04-12',
 '2020-04-22',
 '2020-04-16',
 '2020-03-29',
 '2020-05-01',
 '2020-05-04',
 '2020-05-10',
 '2020-04-10',
 '2020-05-01',
 '2020-03-27',
 '2020-04-08',
 '2020-07-19',
 '2020-04-12',
 '2020-04-17',
 '2020-04-10',
 '2020-03-17',
 '2020-04-05',
 '2020-08-08',
 '2020-05-23',
 '2020-05-01',
 '2020-05-19',
 '2020-04-01',
 '2020-04-06',
 '2020-04-30',
 '2020-05-05',
 '2020-06-01',
 '2020-06-17',
 '2020-04-28',
 '2020-04-17',
 '2020-03-30',
 '2020-03-31',
 '2020-04-01',
 '2020-04-15',
 '2020-04-15',
 '2020-04-23',
 '2020-04-01',
 '2020-07-25',
 '2020-05-01',
 '2020-04-21',
 '2020-04-30',
 '2020-04-16',
 '2020-04-09',
 '2020-05-01',
 '2020-04-13',
 '2020-04-09',
 '2020-04-10',
 '2020-05-01',
 '2020-07-24',
 '2020-04-28',
 '2020-05-01',
 '2020-03-21',
 '2020-05-27',
 '2020-04-11',
 '2020-03-31',
 '2020-04-09',
 '2020-05-03',
 '2020-05-26',
 '2020-04-08',
 '2020-03-30',
 '2020-04-11',
 '2020-05-29',
 '2020-04-06',
 '2020-04-05',
 '2020-04-07',
 '2020-05-29',
 '2020-06-04',
 '2020-04-03',
 '2020-06-04',
 '2020-05-11',
 '2020-06-20',
 '2020-04-12',
 '2020-05-01',
 '2020-04-17',
 '2020-05-26',
 '2020-04-28',
 '2020-05-07',
 '2020-04-19',
 '2020-03-30',
 '2020-05-07',
 '2020-04-13',
 '2020-06-08',
 '2020-03-27',
 '2020-04-02',
 '2020-04-28',
 '2020-06-22',
 '2020-04-09',
 '2020-05-01',
 '2020-05-02',
 '2020-04-09']

## Get date of first min. gov response that is >14

In [9]:
# for loop
dateMin_list = []

for country in countries:
    countryLoc = merged_covid.loc[merged_covid['location'] == country]
    minLoc = countryLoc.loc[countryLoc['GovernmentResponseIndex_updated'] > 14]
    
    indexMin = minLoc.index[0]
    dateMin = merged_covid.iloc[indexMin,1]
    dateMin_list.append(dateMin)

print(dateMin_list)

# ensure got date for each country
print(len(dateMin_list))

['2020-03-01', '2020-03-09', '2020-03-12', '2020-03-24', '2020-03-04', '2020-03-19', '2020-01-25', '2020-02-25', '2020-02-28', '2020-02-09', '2020-03-04', '2020-03-18', '2020-04-09', '2020-02-26', '2020-03-24', '2020-03-17', '2020-03-06', '2020-03-12', '2020-03-06', '2020-04-01', '2020-03-12', '2020-03-10', '2020-03-08', '2020-03-12', '2020-04-01', '2020-03-13', '2020-03-18', '2020-03-11', '2020-03-21', '2020-03-26', '2020-03-20', '2020-03-15', '2020-01-15', '2020-03-09', '2020-03-19', '2020-03-07', '2020-03-16', '2020-02-03', '2020-03-12', '2020-03-10', '2020-03-01', '2020-03-11', '2020-03-03', '2020-03-19', '2020-03-16', '2020-03-13', '2020-03-15', '2020-03-19', '2020-03-22', '2020-03-12', '2020-03-16', '2020-03-11', '2020-02-27', '2020-02-25', '2020-03-13', '2020-03-18', '2020-02-26', '2020-01-27', '2020-03-15', '2020-03-05', '2020-03-19', '2020-03-15', '2020-03-14', '2020-03-13', '2020-03-20', '2020-03-12', '2020-01-31', '2020-03-04', '2020-03-09', '2020-01-31', '2020-02-03', '2020-02-26', '2020-02-24', '2020-02-29', '2020-02-09', '2020-01-31', '2020-03-12', '2020-02-04', '2020-03-15', '2020-03-13', '2020-03-13', '2020-03-01', '2020-03-19', '2020-03-25', '2020-03-12', '2020-02-28', '2020-05-15', '2020-03-17', '2020-03-25', '2020-03-12', '2020-03-05', '2020-03-21', '2020-04-03', '2020-01-24', '2020-03-26', '2020-03-15', '2020-03-20', '2020-03-23', '2020-03-11', '2020-03-10', '2020-03-13', '2020-03-23', '2020-03-17', '2020-03-15', '2020-01-24', '2020-03-09', '2020-02-28', '2020-04-15', '2020-03-21', '2020-02-28', '2020-03-11', '2020-02-03', '2020-02-23', '2020-03-06', '2020-03-10', '2020-03-21', '2020-03-07', '2020-03-06', '2020-01-31', '2020-03-10', '2020-03-01', '2020-03-28', '2020-03-08', '2020-03-08', '2020-03-05', '2020-03-15', '2020-03-03', '2020-03-14', '2020-03-06', '2020-03-15', '2020-04-01', '2020-01-20', '2020-03-07', '2020-03-05', '2020-03-19', '2020-03-07', '2020-02-01', '2020-01-31', '2020-02-06', '2020-03-14', '2020-03-15', '2020-03-15', '2020-03-09', '2020-02-25', '2020-05-01', '2020-03-17', '2020-03-06', '2020-03-22', '2020-03-16', '2020-03-13', '2020-03-09', '2020-03-12', '2020-03-22', '2020-03-12', '2020-03-01', '2020-01-31', '2020-03-02', '2020-03-15', '2020-03-16', '2020-03-15', '2020-01-29', '2020-04-10', '2020-03-19', '2020-03-21']
164

## Get  (1) time (days) from min. gov response (>14) to max. gov response
## and (2) difference between max & min government response 
## for each country

In [10]:
grp_df = merged_covid.groupby('location').max()
grp_df['minDate'] = dateMin_list
grp_df['maxDate'] = dateMax_list
grp_df['maxValue'] = maxValue_list

# get difference between max & min government response for each country
grp_df['changeGovResp'] = grp_df['maxValue'] - 14

display(grp_df)
# check data types of columns
grp_df.dtypes

,primary_key_reaction,date_updated,iso_code,continent,population,population_density,median_age,new_cases,percentage_of_Pop_New_Cases,new_deaths,...,GovernmentResponseIndex_updated,percentage_change_GovernmentResponse,ContainmentHealthIndex_updated,percentage_change_ContainmentHealth,EconomicSupportIndex_updated,percentage_change_EconomicSupport,minDate,maxDate,maxValue,changeGovResp
location,,,,,,,,,,,,,,,,,,,,,
Afghanistan,AFG2020-08-31,2020-08-31,AFG,Asia,38928341.0,54.422,18.6,1063.0,0.002731,56.0,...,64.74,110.509031,76.52,110.562891,0.0,0.000000,2020-03-01,2020-04-12,64.74,50.74
Albania,ALB2020-08-31,2020-08-31,ALB,Europe,2877800.0,104.871,38.0,178.0,0.006185,6.0,...,81.41,157.881773,84.09,157.956915,75.0,200.000000,2020-03-09,2020-05-26,81.41,67.41
Algeria,DZA2020-08-31,2020-08-31,DZA,Africa,43851043.0,17.348,29.1,675.0,0.001539,42.0,...,78.85,199.740260,84.09,199.780220,62.5,66.666667,2020-03-12,2020-08-08,78.85,64.85
Angola,AGO2020-08-31,2020-08-31,AGO,Africa,32866268.0,23.890,16.8,180.0,0.000548,6.0,...,75.64,154.992200,80.30,155.016502,75.0,50.000000,2020-03-24,2020-04-09,75.64,61.64
Argentina,ARG2020-08-31,2020-08-31,ARG,South America,45195777.0,16.177,31.9,11730.0,0.025954,323.0,...,91.03,133.420026,93.94,133.333333,75.0,200.000000,2020-03-04,2020-03-25,91.03,77.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,VEN2020-08-31,2020-08-31,VEN,South America,28435943.0,36.253,29.0,2133.0,0.007501,17.0,...,75.64,36.661466,80.30,36.677668,50.0,0.000000,2020-03-15,2020-06-22,75.64,61.64
Vietnam,VNM2020-08-31,2020-08-31,VNM,Asia,97338583.0,308.127,32.6,50.0,0.000051,4.0,...,85.90,314.031180,96.97,314.528302,50.0,100.000000,2020-01-29,2020-04-09,85.90,71.90
Yemen,YEM2020-08-31,2020-08-31,YEM,Asia,29825968.0,53.508,20.3,116.0,0.000389,52.0,...,40.38,29.528536,47.73,29.552955,0.0,0.000000,2020-04-10,2020-05-01,40.38,26.38
Zambia,ZMB2020-08-31,2020-08-31,ZMB,Africa,18383956.0,22.995,17.7,527.0,0.002867,40.0,...,63.14,61.817347,70.08,61.762422,25.0,0.000000,2020-03-19,2020-05-02,63.14,49.14
Zimbabwe,ZWE2020-08-31,2020-08-31,ZWE,Africa,14862927.0,42.729,19.6,490.0,0.003297,18.0,...,71.15,63.338534,79.55,63.308403,25.0,0.000000,2020-03-21,2020-04-09,71.15,57.15

primary_key_reaction                     object
date_updated                             object
iso_code                                 object
continent                                object
population                              float64
population_density                      float64
median_age                              float64
new_cases                               float64
percentage_of_Pop_New_Cases             float64
new_deaths                              float64
percentage_of_Pop_New_Deaths            float64
new_tests                               float64
percentage_of_Pop_New_Tests             float64
total_cases_updated                     float64
percentage_of_Pop_Total_Cases           float64
total_deaths_updated                    float64
percentage_of_Pop_Total_Deaths          float64
total_tests_updated                     float64
percentage_of_Pop_Total_Tests           float64
primary_key_response                     object
StringencyIndex_updated                 float64
percentage_change_stringency            float64
StringencyLegacyIndex_updated           float64
GovernmentResponseIndex_updated         float64
percentage_change_GovernmentResponse    float64
ContainmentHealthIndex_updated          float64
percentage_change_ContainmentHealth     float64
EconomicSupportIndex_updated            float64
percentage_change_EconomicSupport       float64
minDate                                  object
maxDate                                  object
maxValue                                float64
changeGovResp                           float64
dtype: object

In [11]:
# convert dates to datetime
grp_df['minDate'] = pd.to_datetime(grp_df['minDate'])
grp_df['maxDate'] = pd.to_datetime(grp_df['maxDate'])

# get time (days) from min. to max. gov response
grp_df['ramp_up_duration'] = grp_df['maxDate'] - grp_df['minDate']
display(grp_df.dtypes)

# ensure data types have been converted
grp_df

primary_key_reaction                             object
date_updated                                     object
iso_code                                         object
continent                                        object
population                                      float64
population_density                              float64
median_age                                      float64
new_cases                                       float64
percentage_of_Pop_New_Cases                     float64
new_deaths                                      float64
percentage_of_Pop_New_Deaths                    float64
new_tests                                       float64
percentage_of_Pop_New_Tests                     float64
total_cases_updated                             float64
percentage_of_Pop_Total_Cases                   float64
total_deaths_updated                            float64
percentage_of_Pop_Total_Deaths                  float64
total_tests_updated                             float64
percentage_of_Pop_Total_Tests                   float64
primary_key_response                             object
StringencyIndex_updated                         float64
percentage_change_stringency                    float64
StringencyLegacyIndex_updated                   float64
GovernmentResponseIndex_updated                 float64
percentage_change_GovernmentResponse            float64
ContainmentHealthIndex_updated                  float64
percentage_change_ContainmentHealth             float64
EconomicSupportIndex_updated                    float64
percentage_change_EconomicSupport               float64
minDate                                  datetime64[ns]
maxDate                                  datetime64[ns]
maxValue                                        float64
changeGovResp                                   float64
ramp_up_duration                        timedelta64[ns]
dtype: object

,primary_key_reaction,date_updated,iso_code,continent,population,population_density,median_age,new_cases,percentage_of_Pop_New_Cases,new_deaths,...,percentage_change_GovernmentResponse,ContainmentHealthIndex_updated,percentage_change_ContainmentHealth,EconomicSupportIndex_updated,percentage_change_EconomicSupport,minDate,maxDate,maxValue,changeGovResp,ramp_up_duration
location,,,,,,,,,,,,,,,,,,,,,
Afghanistan,AFG2020-08-31,2020-08-31,AFG,Asia,38928341.0,54.422,18.6,1063.0,0.002731,56.0,...,110.509031,76.52,110.562891,0.0,0.000000,2020-03-01,2020-04-12,64.74,50.74,42 days
Albania,ALB2020-08-31,2020-08-31,ALB,Europe,2877800.0,104.871,38.0,178.0,0.006185,6.0,...,157.881773,84.09,157.956915,75.0,200.000000,2020-03-09,2020-05-26,81.41,67.41,78 days
Algeria,DZA2020-08-31,2020-08-31,DZA,Africa,43851043.0,17.348,29.1,675.0,0.001539,42.0,...,199.740260,84.09,199.780220,62.5,66.666667,2020-03-12,2020-08-08,78.85,64.85,149 days
Angola,AGO2020-08-31,2020-08-31,AGO,Africa,32866268.0,23.890,16.8,180.0,0.000548,6.0,...,154.992200,80.30,155.016502,75.0,50.000000,2020-03-24,2020-04-09,75.64,61.64,16 days
Argentina,ARG2020-08-31,2020-08-31,ARG,South America,45195777.0,16.177,31.9,11730.0,0.025954,323.0,...,133.420026,93.94,133.333333,75.0,200.000000,2020-03-04,2020-03-25,91.03,77.03,21 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,VEN2020-08-31,2020-08-31,VEN,South America,28435943.0,36.253,29.0,2133.0,0.007501,17.0,...,36.661466,80.30,36.677668,50.0,0.000000,2020-03-15,2020-06-22,75.64,61.64,99 days
Vietnam,VNM2020-08-31,2020-08-31,VNM,Asia,97338583.0,308.127,32.6,50.0,0.000051,4.0,...,314.031180,96.97,314.528302,50.0,100.000000,2020-01-29,2020-04-09,85.90,71.90,71 days
Yemen,YEM2020-08-31,2020-08-31,YEM,Asia,29825968.0,53.508,20.3,116.0,0.000389,52.0,...,29.528536,47.73,29.552955,0.0,0.000000,2020-04-10,2020-05-01,40.38,26.38,21 days
Zambia,ZMB2020-08-31,2020-08-31,ZMB,Africa,18383956.0,22.995,17.7,527.0,0.002867,40.0,...,61.817347,70.08,61.762422,25.0,0.000000,2020-03-19,2020-05-02,63.14,49.14,44 days
Zimbabwe,ZWE2020-08-31,2020-08-31,ZWE,Africa,14862927.0,42.729,19.6,490.0,0.003297,18.0,...,63.338534,79.55,63.308403,25.0,0.000000,2020-03-21,2020-04-09,71.15,57.15,19 days

In [12]:
# reset index
grp_df = grp_df.reset_index()
grp_df

# reorder dataframe
rampUp_df = grp_df[['location','primary_key_reaction','iso_code','minDate','maxDate','maxValue','changeGovResp','ramp_up_duration','population','population_density','median_age']]
rampUp_df

,location,primary_key_reaction,iso_code,minDate,maxDate,maxValue,changeGovResp,ramp_up_duration,population,population_density,median_age
0,Afghanistan,AFG2020-08-31,AFG,2020-03-01,2020-04-12,64.74,50.74,42 days,38928341.0,54.422,18.6
1,Albania,ALB2020-08-31,ALB,2020-03-09,2020-05-26,81.41,67.41,78 days,2877800.0,104.871,38.0
2,Algeria,DZA2020-08-31,DZA,2020-03-12,2020-08-08,78.85,64.85,149 days,43851043.0,17.348,29.1
3,Angola,AGO2020-08-31,AGO,2020-03-24,2020-04-09,75.64,61.64,16 days,32866268.0,23.890,16.8
4,Argentina,ARG2020-08-31,ARG,2020-03-04,2020-03-25,91.03,77.03,21 days,45195777.0,16.177,31.9
...,...,...,...,...,...,...,...,...,...,...,...
159,Venezuela,VEN2020-08-31,VEN,2020-03-15,2020-06-22,75.64,61.64,99 days,28435943.0,36.253,29.0
160,Vietnam,VNM2020-08-31,VNM,2020-01-29,2020-04-09,85.90,71.90,71 days,97338583.0,308.127,32.6
161,Yemen,YEM2020-08-31,YEM,2020-04-10,2020-05-01,40.38,26.38,21 days,29825968.0,53.508,20.3
162,Zambia,ZMB2020-08-31,ZMB,2020-03-19,2020-05-02,63.14,49.14,44 days,18383956.0,22.995,17.7
163,Zimbabwe,ZWE2020-08-31,ZWE,2020-03-21,2020-04-09,71.15,57.15,19 days,14862927.0,42.729,19.6

In [13]:
# save to csv if wished
# rampUp_df.to_csv("rampUpDuration.csv")

## Get date of first covid case for each country

In [14]:
# for loop to get index of first covid case for each country
index_list = []

for country in countries:
    countryLoc = merged_covid.loc[merged_covid['location'] == country]
    nonZero_df = countryLoc[(countryLoc['new_cases'] != 0)]
    if nonZero_df.empty == False:        
        index = nonZero_df.index[nonZero_df['new_cases'] > 0].to_list()[0]
    index_list.append(index)

index_list

[55,
 244,
 476,
 664,
 849,
 1030,
 1221,
 1497,
 1744,
 1983,
 2178,
 2354,
 2579,
 2799,
 3009,
 3170,
 3338,
 3512,
 3685,
 3859,
 4068,
 4256,
 4430,
 4605,
 4777,
 4957,
 5174,
 5373,
 5592,
 5756,
 5925,
 6090,
 6272,
 6516,
 6694,
 6863,
 7040,
 7267,
 7455,
 7625,
 7859,
 8042,
 8271,
 8458,
 8685,
 8928,
 9157,
 9356,
 9522,
 9743,
 9929,
 10150,
 10344,
 10583,
 10803,
 10974,
 11198,
 11412,
 11629,
 11857,
 12044,
 12210,
 12380,
 12550,
 12720,
 12885,
 12885,
 13075,
 13314,
 13528,
 13804,
 14037,
 14286,
 14535,
 14771,
 14993,
 15207,
 15393,
 15623,
 15803,
 15981,
 16206,
 16396,
 16562,
 16725,
 16959,
 17151,
 17260,
 17428,
 17646,
 17892,
 18076,
 18240,
 18415,
 18635,
 18794,
 18964,
 19188,
 19373,
 19548,
 19744,
 19926,
 20090,
 20251,
 20445,
 20723,
 20967,
 21153,
 21319,
 21541,
 21784,
 22026,
 22272,
 22459,
 22638,
 22813,
 22978,
 23163,
 23370,
 23585,
 23766,
 23948,
 24165,
 24406,
 24624,
 24837,
 25007,
 25187,
 25379,
 25557,
 25727,
 25903,
 26124,
 26301,
 26480,
 26676,
 26874,
 27130,
 27369,
 27586,
 27757,
 27922,
 28123,
 28392,
 28580,
 28703,
 28883,
 29115,
 29281,
 29459,
 29631,
 29808,
 29979,
 30142,
 30344,
 30593,
 30826,
 31050,
 31220,
 31389,
 31582,
 31803,
 31947,
 32113]

In [15]:
# using the index, get the date for the first covid case for each country
newCases_startDate = []

for index in index_list:
    startDate = merged_covid.iloc[index,1]
    newCases_startDate.append(startDate)

newCases_startDate

['2020-02-25',
 '2020-03-09',
 '2020-02-26',
 '2020-03-22',
 '2020-03-04',
 '2020-03-13',
 '2020-01-25',
 '2020-02-26',
 '2020-02-29',
 '2020-02-24',
 '2020-03-09',
 '2020-03-18',
 '2020-02-28',
 '2020-02-04',
 '2020-03-24',
 '2020-03-17',
 '2020-03-06',
 '2020-03-12',
 '2020-03-06',
 '2020-04-01',
 '2020-02-26',
 '2020-03-10',
 '2020-03-08',
 '2020-03-11',
 '2020-04-01',
 '2020-01-28',
 '2020-03-07',
 '2020-01-26',
 '2020-03-21',
 '2020-03-16',
 '2020-03-20',
 '2020-03-04',
 '2020-01-03',
 '2020-03-07',
 '2020-03-16',
 '2020-03-07',
 '2020-03-12',
 '2020-02-26',
 '2020-03-12',
 '2020-03-10',
 '2020-03-02',
 '2020-03-11',
 '2020-02-27',
 '2020-03-19',
 '2020-03-02',
 '2020-03-01',
 '2020-02-15',
 '2020-03-19',
 '2020-03-22',
 '2020-02-28',
 '2020-03-14',
 '2020-03-20',
 '2020-01-30',
 '2020-01-25',
 '2020-03-13',
 '2020-03-18',
 '2020-02-27',
 '2020-01-28',
 '2020-03-13',
 '2020-02-27',
 '2020-03-19',
 '2020-03-15',
 '2020-03-14',
 '2020-03-13',
 '2020-03-20',
 '2020-03-12',
 '2020-03-12',
 '2020-03-05',
 '2020-02-29',
 '2020-01-30',
 '2020-03-02',
 '2020-02-20',
 '2020-02-25',
 '2020-03-01',
 '2020-02-22',
 '2020-01-31',
 '2020-03-12',
 '2020-01-15',
 '2020-03-03',
 '2020-03-15',
 '2020-03-14',
 '2020-02-24',
 '2020-03-19',
 '2020-03-25',
 '2020-03-03',
 '2020-02-22',
 '2020-05-15',
 '2020-03-17',
 '2020-03-25',
 '2020-02-28',
 '2020-03-01',
 '2020-03-21',
 '2020-04-03',
 '2020-01-25',
 '2020-03-26',
 '2020-03-15',
 '2020-03-20',
 '2020-02-29',
 '2020-03-08',
 '2020-03-10',
 '2020-03-03',
 '2020-03-23',
 '2020-03-24',
 '2020-03-15',
 '2020-01-25',
 '2020-02-28',
 '2020-02-28',
 '2020-03-19',
 '2020-03-21',
 '2020-02-28',
 '2020-02-27',
 '2020-02-25',
 '2020-02-27',
 '2020-03-06',
 '2020-03-10',
 '2020-03-21',
 '2020-03-08',
 '2020-03-07',
 '2020-01-30',
 '2020-03-04',
 '2020-03-03',
 '2020-03-28',
 '2020-03-01',
 '2020-02-27',
 '2020-02-01',
 '2020-03-15',
 '2020-03-03',
 '2020-03-03',
 '2020-03-07',
 '2020-03-15',
 '2020-04-01',
 '2020-01-24',
 '2020-03-07',
 '2020-03-05',
 '2020-03-17',
 '2020-03-06',
 '2020-01-20',
 '2020-02-01',
 '2020-01-28',
 '2020-03-14',
 '2020-03-15',
 '2020-03-15',
 '2020-02-01',
 '2020-02-26',
 '2020-05-01',
 '2020-03-17',
 '2020-01-13',
 '2020-03-22',
 '2020-03-07',
 '2020-03-13',
 '2020-03-03',
 '2020-03-12',
 '2020-03-22',
 '2020-03-04',
 '2020-01-27',
 '2020-02-01',
 '2020-01-21',
 '2020-03-15',
 '2020-03-16',
 '2020-03-15',
 '2020-01-24',
 '2020-04-10',
 '2020-03-19',
 '2020-03-21']

In [16]:
# add date of first case for each country to the dataframe
rampUp_df['newCases_startDate'] = newCases_startDate
rampUp_df['newCases_startDate'] = pd.to_datetime(rampUp_df['newCases_startDate'])

# check the data types
rampUp_df.dtypes

<ipython-input-16-bc66fd33c929>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rampUp_df['newCases_startDate'] = newCases_startDate
<ipython-input-16-bc66fd33c929>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rampUp_df['newCases_startDate'] = pd.to_datetime(rampUp_df['newCases_startDate'])

location                         object
primary_key_reaction             object
iso_code                         object
minDate                  datetime64[ns]
maxDate                  datetime64[ns]
maxValue                        float64
changeGovResp                   float64
ramp_up_duration        timedelta64[ns]
population                      float64
population_density              float64
median_age                      float64
newCases_startDate       datetime64[ns]
dtype: object

## Determine the time (days) from start of gov. response to first covid case for each country
### Positive number means gov resp started AFTER first case
### Negative number means gov resp started BEFORE first case

In [17]:
rampUp_df['CaseVsResp_Interval'] = rampUp_df['newCases_startDate'] - rampUp_df['minDate']

# check dataframe
display(rampUp_df)
display(rampUp_df.describe())
list(rampUp_df.columns)

<ipython-input-17-f9795f842de4>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rampUp_df['CaseVsResp_Interval'] = rampUp_df['newCases_startDate'] - rampUp_df['minDate']

,location,primary_key_reaction,iso_code,minDate,maxDate,maxValue,changeGovResp,ramp_up_duration,population,population_density,median_age,newCases_startDate,CaseVsResp_Interval
0,Afghanistan,AFG2020-08-31,AFG,2020-03-01,2020-04-12,64.74,50.74,42 days,38928341.0,54.422,18.6,2020-02-25,-5 days
1,Albania,ALB2020-08-31,ALB,2020-03-09,2020-05-26,81.41,67.41,78 days,2877800.0,104.871,38.0,2020-03-09,0 days
2,Algeria,DZA2020-08-31,DZA,2020-03-12,2020-08-08,78.85,64.85,149 days,43851043.0,17.348,29.1,2020-02-26,-15 days
3,Angola,AGO2020-08-31,AGO,2020-03-24,2020-04-09,75.64,61.64,16 days,32866268.0,23.890,16.8,2020-03-22,-2 days
4,Argentina,ARG2020-08-31,ARG,2020-03-04,2020-03-25,91.03,77.03,21 days,45195777.0,16.177,31.9,2020-03-04,0 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,Venezuela,VEN2020-08-31,VEN,2020-03-15,2020-06-22,75.64,61.64,99 days,28435943.0,36.253,29.0,2020-03-15,0 days
160,Vietnam,VNM2020-08-31,VNM,2020-01-29,2020-04-09,85.90,71.90,71 days,97338583.0,308.127,32.6,2020-01-24,-5 days
161,Yemen,YEM2020-08-31,YEM,2020-04-10,2020-05-01,40.38,26.38,21 days,29825968.0,53.508,20.3,2020-04-10,0 days
162,Zambia,ZMB2020-08-31,ZMB,2020-03-19,2020-05-02,63.14,49.14,44 days,18383956.0,22.995,17.7,2020-03-19,0 days
163,Zimbabwe,ZWE2020-08-31,ZWE,2020-03-21,2020-04-09,71.15,57.15,19 days,14862927.0,42.729,19.6,2020-03-21,0 days

,maxValue,changeGovResp,ramp_up_duration,population,population_density,median_age,CaseVsResp_Interval
count,164.000000,164.000000,164,1.640000e+02,164.000000,164.000000,164
mean,75.783780,61.783780,52 days 04:32:11.707317,4.688436e+07,235.514055,30.518293,-5 days +23:42:26.341463
std,12.672464,12.672464,37 days 04:13:27.677216,1.599393e+08,838.374632,9.276511,11 days 23:15:01.470996
min,14.100000,0.100000,0 days 00:00:00,9.834000e+04,1.980000,15.100000,-53 days +00:00:00
25%,70.350000,56.350000,26 days 00:00:00,4.303717e+06,31.167250,22.150000,-6 days +00:00:00
50%,78.850000,64.850000,42 days 12:00:00,1.056602e+07,80.819000,29.600000,0 days 00:00:00
75%,84.620000,70.620000,68 days 00:00:00,3.380537e+07,167.755250,38.925000,0 days 00:00:00
max,96.150000,82.150000,191 days 00:00:00,1.439324e+09,7915.731000,48.200000,41 days 00:00:00

['location',
 'primary_key_reaction',
 'iso_code',
 'minDate',
 'maxDate',
 'maxValue',
 'changeGovResp',
 'ramp_up_duration',
 'population',
 'population_density',
 'median_age',
 'newCases_startDate',
 'CaseVsResp_Interval']

## include avg. max. gov response starting Apr 1, 2020 (and continuing until Aug 31, 2020, inclusive)

In [18]:
# preview dataframe (df)
display(avgMaxGovResp)

join_df = rampUp_df.merge(avgMaxGovResp, how="inner", on="location")
join_df = join_df.rename(columns={"GovernmentResponseIndex_updated":"AvgMaxGovResp_StartApr1"})

# ensure join & renaming occurred properly
join_df

        location  GovernmentResponseIndex_updated
0       Honduras                        86.684510
1      Argentina                        85.190196
2    El Salvador                        84.830980
3       Colombia                        84.497516
4          Nepal                        83.451307
..           ...                              ...
159        Yemen                        32.003750
160     Tanzania                        27.344510
161      Burundi                        26.477778
162      Belarus                        22.989020
163    Nicaragua                        12.116340

[164 rows x 2 columns]

,location,primary_key_reaction,iso_code,minDate,maxDate,maxValue,changeGovResp,ramp_up_duration,population,population_density,median_age,newCases_startDate,CaseVsResp_Interval,AvgMaxGovResp_StartApr1
0,Afghanistan,AFG2020-08-31,AFG,2020-03-01,2020-04-12,64.74,50.74,42 days,38928341.0,54.422,18.6,2020-02-25,-5 days,60.578889
1,Albania,ALB2020-08-31,ALB,2020-03-09,2020-05-26,81.41,67.41,78 days,2877800.0,104.871,38.0,2020-03-09,0 days,68.489542
2,Algeria,DZA2020-08-31,DZA,2020-03-12,2020-08-08,78.85,64.85,149 days,43851043.0,17.348,29.1,2020-02-26,-15 days,66.171046
3,Angola,AGO2020-08-31,AGO,2020-03-24,2020-04-09,75.64,61.64,16 days,32866268.0,23.890,16.8,2020-03-22,-2 days,67.044379
4,Argentina,ARG2020-08-31,ARG,2020-03-04,2020-03-25,91.03,77.03,21 days,45195777.0,16.177,31.9,2020-03-04,0 days,85.190196
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,Venezuela,VEN2020-08-31,VEN,2020-03-15,2020-06-22,75.64,61.64,99 days,28435943.0,36.253,29.0,2020-03-15,0 days,72.385621
160,Vietnam,VNM2020-08-31,VNM,2020-01-29,2020-04-09,85.90,71.90,71 days,97338583.0,308.127,32.6,2020-01-24,-5 days,67.005033
161,Yemen,YEM2020-08-31,YEM,2020-04-10,2020-05-01,40.38,26.38,21 days,29825968.0,53.508,20.3,2020-04-10,0 days,32.003750
162,Zambia,ZMB2020-08-31,ZMB,2020-03-19,2020-05-02,63.14,49.14,44 days,18383956.0,22.995,17.7,2020-03-19,0 days,48.770523
163,Zimbabwe,ZWE2020-08-31,ZWE,2020-03-21,2020-04-09,71.15,57.15,19 days,14862927.0,42.729,19.6,2020-03-21,0 days,66.137255

## Find date & value of max. new cases (peak of bell curve) for each country

In [19]:
# for loop
indexMaxNewCases_list = []
valueMaxNewCases_list = []
dateMaxNewCases_list = []

for country in countries:
    countryLoc = merged_covid.loc[merged_covid['location'] == country]
    maxNewCases_index = countryLoc['new_cases'].idxmax()
    maxNewCases_value = countryLoc['new_cases'].max()
    
    indexMaxNewCases_list.append(maxNewCases_index)
    valueMaxNewCases_list.append(maxNewCases_value)

# print to preview index and value of max. new cases for each country
# print(indexMaxNewCases_list)
# print(valueMaxNewCases_list)

for index in indexMaxNewCases_list:
    maxNewCases_date = merged_covid.iloc[index,1]
    dateMaxNewCases_list.append(maxNewCases_date)

# list of dates for max. value of new cases for each country
dateMaxNewCases_list

['2020-05-16',
 '2020-08-25',
 '2020-07-25',
 '2020-08-06',
 '2020-08-30',
 '2020-08-20',
 '2020-07-31',
 '2020-03-27',
 '2020-06-25',
 '2020-06-13',
 '2020-07-03',
 '2020-08-02',
 '2020-04-30',
 '2020-04-11',
 '2020-08-30',
 '2020-07-18',
 '2020-08-31',
 '2020-08-16',
 '2020-07-31',
 '2020-08-25',
 '2020-07-30',
 '2020-03-13',
 '2020-08-27',
 '2020-04-06',
 '2020-06-21',
 '2020-03-23',
 '2020-07-06',
 '2020-05-04',
 '2020-07-13',
 '2020-06-09',
 '2020-05-08',
 '2020-06-18',
 '2020-02-13',
 '2020-08-20',
 '2020-07-18',
 '2020-08-30',
 '2020-06-22',
 '2020-08-27',
 '2020-08-11',
 '2020-04-02',
 '2020-08-22',
 '2020-06-26',
 '2020-04-08',
 '2020-05-21',
 '2020-07-27',
 '2020-04-27',
 '2020-06-20',
 '2020-08-22',
 '2020-06-15',
 '2020-03-27',
 '2020-08-22',
 '2020-04-04',
 '2020-04-05',
 '2020-04-01',
 '2020-06-16',
 '2020-08-20',
 '2020-05-02',
 '2020-03-28',
 '2020-08-02',
 '2020-08-27',
 '2020-08-27',
 '2020-07-19',
 '2020-05-22',
 '2020-08-26',
 '2020-06-06',
 '2020-08-27',
 '2020-01-31',
 '2020-08-31',
 '2020-04-03',
 '2020-08-30',
 '2020-08-30',
 '2020-04-05',
 '2020-08-19',
 '2020-04-10',
 '2020-07-28',
 '2020-03-22',
 '2020-08-31',
 '2020-08-15',
 '2020-08-26',
 '2020-07-01',
 '2020-07-27',
 '2020-05-20',
 '2020-07-18',
 '2020-03-27',
 '2020-03-30',
 '2020-08-20',
 '2020-08-02',
 '2020-06-28',
 '2020-08-18',
 '2020-04-04',
 '2020-03-26',
 '2020-07-23',
 '2020-07-12',
 '2020-06-06',
 '2020-06-05',
 '2020-06-21',
 '2020-04-10',
 '2020-08-02',
 '2020-08-01',
 '2020-05-16',
 '2020-08-20',
 '2020-08-11',
 '2020-08-30',
 '2020-08-24',
 '2020-06-25',
 '2020-04-11',
 '2020-03-31',
 '2020-05-27',
 '2020-04-07',
 '2020-07-02',
 '2020-03-28',
 '2020-07-14',
 '2020-06-14',
 '2020-08-29',
 '2020-07-14',
 '2020-08-13',
 '2020-08-31',
 '2020-08-17',
 '2020-08-11',
 '2020-08-22',
 '2020-04-11',
 '2020-08-02',
 '2020-05-31',
 '2020-08-28',
 '2020-07-18',
 '2020-08-26',
 '2020-06-18',
 '2020-08-13',
 '2020-07-27',
 '2020-07-07',
 '2020-05-25',
 '2020-04-21',
 '2020-08-22',
 '2020-03-29',
 '2020-05-29',
 '2020-07-25',
 '2020-02-29',
 '2020-08-24',
 '2020-07-10',
 '2020-06-17',
 '2020-08-19',
 '2020-07-30',
 '2020-06-26',
 '2020-03-28',
 '2020-05-29',
 '2020-04-30',
 '2020-03-31',
 '2020-04-17',
 '2020-08-29',
 '2020-08-27',
 '2020-08-20',
 '2020-04-12',
 '2020-08-24',
 '2020-08-26',
 '2020-05-23',
 '2020-04-24',
 '2020-07-25',
 '2020-03-30',
 '2020-08-18',
 '2020-08-12',
 '2020-07-31',
 '2020-06-16',
 '2020-07-18',
 '2020-08-02']

## Find time (days) from first case to max. new cases for each country

In [20]:
join_df['MaxNewCases_date'] = dateMaxNewCases_list
join_df['MaxNewCases_value'] = valueMaxNewCases_list

join_df['MaxNewCases_date'] = pd.to_datetime(join_df['MaxNewCases_date'])
join_df['StartToMaxNewCases_Interval'] = join_df['MaxNewCases_date'] - join_df['minDate']

# ensure proper join and check data types (dtypes)
display(join_df)
join_df.dtypes

,location,primary_key_reaction,iso_code,minDate,maxDate,maxValue,changeGovResp,ramp_up_duration,population,population_density,median_age,newCases_startDate,CaseVsResp_Interval,AvgMaxGovResp_StartApr1,MaxNewCases_date,MaxNewCases_value,StartToMaxNewCases_Interval
0,Afghanistan,AFG2020-08-31,AFG,2020-03-01,2020-04-12,64.74,50.74,42 days,38928341.0,54.422,18.6,2020-02-25,-5 days,60.578889,2020-05-16,1063.0,76 days
1,Albania,ALB2020-08-31,ALB,2020-03-09,2020-05-26,81.41,67.41,78 days,2877800.0,104.871,38.0,2020-03-09,0 days,68.489542,2020-08-25,178.0,169 days
2,Algeria,DZA2020-08-31,DZA,2020-03-12,2020-08-08,78.85,64.85,149 days,43851043.0,17.348,29.1,2020-02-26,-15 days,66.171046,2020-07-25,675.0,135 days
3,Angola,AGO2020-08-31,AGO,2020-03-24,2020-04-09,75.64,61.64,16 days,32866268.0,23.890,16.8,2020-03-22,-2 days,67.044379,2020-08-06,180.0,135 days
4,Argentina,ARG2020-08-31,ARG,2020-03-04,2020-03-25,91.03,77.03,21 days,45195777.0,16.177,31.9,2020-03-04,0 days,85.190196,2020-08-30,11730.0,179 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,Venezuela,VEN2020-08-31,VEN,2020-03-15,2020-06-22,75.64,61.64,99 days,28435943.0,36.253,29.0,2020-03-15,0 days,72.385621,2020-08-12,2133.0,150 days
160,Vietnam,VNM2020-08-31,VNM,2020-01-29,2020-04-09,85.90,71.90,71 days,97338583.0,308.127,32.6,2020-01-24,-5 days,67.005033,2020-07-31,50.0,184 days
161,Yemen,YEM2020-08-31,YEM,2020-04-10,2020-05-01,40.38,26.38,21 days,29825968.0,53.508,20.3,2020-04-10,0 days,32.003750,2020-06-16,116.0,67 days
162,Zambia,ZMB2020-08-31,ZMB,2020-03-19,2020-05-02,63.14,49.14,44 days,18383956.0,22.995,17.7,2020-03-19,0 days,48.770523,2020-07-18,527.0,121 days
163,Zimbabwe,ZWE2020-08-31,ZWE,2020-03-21,2020-04-09,71.15,57.15,19 days,14862927.0,42.729,19.6,2020-03-21,0 days,66.137255,2020-08-02,490.0,134 days

location                                object
primary_key_reaction                    object
iso_code                                object
minDate                         datetime64[ns]
maxDate                         datetime64[ns]
maxValue                               float64
changeGovResp                          float64
ramp_up_duration               timedelta64[ns]
population                             float64
population_density                     float64
median_age                             float64
newCases_startDate              datetime64[ns]
CaseVsResp_Interval            timedelta64[ns]
AvgMaxGovResp_StartApr1                float64
MaxNewCases_date                datetime64[ns]
MaxNewCases_value                      float64
StartToMaxNewCases_Interval    timedelta64[ns]
dtype: object

## Find value and date of max new deaths for each country

In [21]:
# for loop
indexMaxNewDeaths_list = []
valueMaxNewDeaths_list = []
dateMaxNewDeaths_list = []

for country in countries:
    countryLoc = merged_covid.loc[merged_covid['location'] == country]
    maxNewDeaths_index = countryLoc['new_deaths'].idxmax()
    maxNewDeaths_value = countryLoc['new_deaths'].max()
    
    indexMaxNewDeaths_list.append(maxNewDeaths_index)
    valueMaxNewDeaths_list.append(maxNewDeaths_value)

# print to preview index and value of max. new cases for each country
# print(indexMaxNewCases_list)
# print(valueMaxNewCases_list)

for index in indexMaxNewDeaths_list:
    maxNewDeaths_date = merged_covid.iloc[index,1]
    dateMaxNewDeaths_list.append(maxNewDeaths_date)

# list of dates of max. value of new deaths for each country
dateMaxNewDeaths_list

['2020-07-07',
 '2020-07-26',
 '2020-04-04',
 '2020-07-30',
 '2020-08-26',
 '2020-04-16',
 '2020-08-18',
 '2020-04-23',
 '2020-07-22',
 '2020-06-27',
 '2020-07-01',
 '2020-04-06',
 '2020-07-26',
 '2020-04-09',
 '2020-08-25',
 '2020-06-30',
 '2020-03-06',
 '2020-08-16',
 '2020-07-31',
 '2020-08-27',
 '2020-07-30',
 '2020-03-29',
 '2020-08-27',
 '2020-03-29',
 '2020-04-15',
 '2020-01-01',
 '2020-06-13',
 '2020-06-01',
 '2020-07-01',
 '2020-06-23',
 '2020-05-08',
 '2020-07-18',
 '2020-04-17',
 '2020-08-23',
 '2020-08-17',
 '2020-08-08',
 '2020-06-13',
 '2020-04-20',
 '2020-04-25',
 '2020-03-25',
 '2020-04-15',
 '2020-05-16',
 '2020-04-05',
 '2020-05-26',
 '2020-04-13',
 '2020-05-11',
 '2020-06-16',
 '2020-08-06',
 '2020-03-22',
 '2020-04-03',
 '2020-08-04',
 '2020-08-01',
 '2020-04-22',
 '2020-04-04',
 '2020-06-23',
 '2020-08-20',
 '2020-04-06',
 '2020-04-16',
 '2020-06-21',
 '2020-04-05',
 '2020-04-01',
 '2020-07-30',
 '2020-05-14',
 '2020-08-29',
 '2020-07-11',
 '2020-08-27',
 '2020-01-31',
 '2020-04-24',
 '2020-04-03',
 '2020-06-17',
 '2020-07-23',
 '2020-08-08',
 '2020-06-27',
 '2020-04-26',
 '2020-08-20',
 '2020-03-28',
 '2020-08-26',
 '2020-04-23',
 '2020-03-31',
 '2020-08-10',
 '2020-08-02',
 '2020-05-17',
 '2020-07-18',
 '2020-03-25',
 '2020-04-22',
 '2020-08-26',
 '2020-08-03',
 '2020-07-16',
 '2020-08-04',
 '2020-04-12',
 '2020-04-12',
 '2020-07-17',
 '2020-07-27',
 '2020-03-30',
 '2020-06-05',
 '2020-06-10',
 '2020-04-02',
 '2020-06-04',
 '2020-08-14',
 '2020-03-10',
 '2020-08-20',
 '2020-08-03',
 '2020-04-09',
 '2020-08-24',
 '2020-08-31',
 '2020-04-08',
 '2020-04-14',
 '2020-05-27',
 '2020-04-06',
 '2020-06-17',
 '2020-04-15',
 '2020-08-06',
 '2020-06-20',
 '2020-08-11',
 '2020-07-25',
 '2020-07-29',
 '2020-08-16',
 '2020-08-14',
 '2020-07-13',
 '2020-04-25',
 '2020-04-25',
 '2020-08-16',
 '2020-06-20',
 '2020-08-26',
 '2020-06-19',
 '2020-08-19',
 '2020-07-06',
 '2020-08-07',
 '2020-07-11',
 '2020-03-15',
 '2020-05-15',
 '2020-03-22',
 '2020-04-16',
 '2020-04-06',
 '2020-04-23',
 '2020-07-23',
 '2020-03-20',
 '2020-06-19',
 '2020-03-29',
 '2020-05-30',
 '2020-08-12',
 '2020-07-29',
 '2020-04-10',
 '2020-04-01',
 '2020-05-10',
 '2020-04-30',
 '2020-04-04',
 '2020-03-22',
 '2020-04-17',
 '2020-08-29',
 '2020-04-05',
 '2020-04-20',
 '2020-08-21',
 '2020-08-27',
 '2020-05-11',
 '2020-04-22',
 '2020-04-16',
 '2020-04-03',
 '2020-08-18',
 '2020-08-30',
 '2020-08-12',
 '2020-07-13',
 '2020-07-15',
 '2020-08-13']

## Time (days) from max. new cases to max. new deaths for each country

In [22]:
join_df['MaxNewDeaths_date'] = dateMaxNewDeaths_list
join_df['MaxNewDeaths_value'] = valueMaxNewDeaths_list

join_df['MaxNewDeaths_date'] = pd.to_datetime(join_df['MaxNewDeaths_date'])

join_df['MaxNewCasesToMaxNewDeaths_Interval'] = join_df['MaxNewDeaths_date'] - join_df['MaxNewCases_date']

# check df & dtypes
display(join_df)
join_df.dtypes

,location,primary_key_reaction,iso_code,minDate,maxDate,maxValue,changeGovResp,ramp_up_duration,population,population_density,median_age,newCases_startDate,CaseVsResp_Interval,AvgMaxGovResp_StartApr1,MaxNewCases_date,MaxNewCases_value,StartToMaxNewCases_Interval,MaxNewDeaths_date,MaxNewDeaths_value,MaxNewCasesToMaxNewDeaths_Interval
0,Afghanistan,AFG2020-08-31,AFG,2020-03-01,2020-04-12,64.74,50.74,42 days,38928341.0,54.422,18.6,2020-02-25,-5 days,60.578889,2020-05-16,1063.0,76 days,2020-07-07,56.0,52 days
1,Albania,ALB2020-08-31,ALB,2020-03-09,2020-05-26,81.41,67.41,78 days,2877800.0,104.871,38.0,2020-03-09,0 days,68.489542,2020-08-25,178.0,169 days,2020-07-26,6.0,-30 days
2,Algeria,DZA2020-08-31,DZA,2020-03-12,2020-08-08,78.85,64.85,149 days,43851043.0,17.348,29.1,2020-02-26,-15 days,66.171046,2020-07-25,675.0,135 days,2020-04-04,42.0,-112 days
3,Angola,AGO2020-08-31,AGO,2020-03-24,2020-04-09,75.64,61.64,16 days,32866268.0,23.890,16.8,2020-03-22,-2 days,67.044379,2020-08-06,180.0,135 days,2020-07-30,6.0,-7 days
4,Argentina,ARG2020-08-31,ARG,2020-03-04,2020-03-25,91.03,77.03,21 days,45195777.0,16.177,31.9,2020-03-04,0 days,85.190196,2020-08-30,11730.0,179 days,2020-08-26,323.0,-4 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,Venezuela,VEN2020-08-31,VEN,2020-03-15,2020-06-22,75.64,61.64,99 days,28435943.0,36.253,29.0,2020-03-15,0 days,72.385621,2020-08-12,2133.0,150 days,2020-08-30,17.0,18 days
160,Vietnam,VNM2020-08-31,VNM,2020-01-29,2020-04-09,85.90,71.90,71 days,97338583.0,308.127,32.6,2020-01-24,-5 days,67.005033,2020-07-31,50.0,184 days,2020-08-12,4.0,12 days
161,Yemen,YEM2020-08-31,YEM,2020-04-10,2020-05-01,40.38,26.38,21 days,29825968.0,53.508,20.3,2020-04-10,0 days,32.003750,2020-06-16,116.0,67 days,2020-07-13,52.0,27 days
162,Zambia,ZMB2020-08-31,ZMB,2020-03-19,2020-05-02,63.14,49.14,44 days,18383956.0,22.995,17.7,2020-03-19,0 days,48.770523,2020-07-18,527.0,121 days,2020-07-15,40.0,-3 days
163,Zimbabwe,ZWE2020-08-31,ZWE,2020-03-21,2020-04-09,71.15,57.15,19 days,14862927.0,42.729,19.6,2020-03-21,0 days,66.137255,2020-08-02,490.0,134 days,2020-08-13,18.0,11 days

location                                       object
primary_key_reaction                           object
iso_code                                       object
minDate                                datetime64[ns]
maxDate                                datetime64[ns]
maxValue                                      float64
changeGovResp                                 float64
ramp_up_duration                      timedelta64[ns]
population                                    float64
population_density                            float64
median_age                                    float64
newCases_startDate                     datetime64[ns]
CaseVsResp_Interval                   timedelta64[ns]
AvgMaxGovResp_StartApr1                       float64
MaxNewCases_date                       datetime64[ns]
MaxNewCases_value                             float64
StartToMaxNewCases_Interval           timedelta64[ns]
MaxNewDeaths_date                      datetime64[ns]
MaxNewDeaths_value                            float64
MaxNewCasesToMaxNewDeaths_Interval    timedelta64[ns]
dtype: object

## Time (days) from first new case to max. new deaths for each country

In [23]:
join_df['FirstNewCaseToMaxNewDeaths'] = join_df['MaxNewDeaths_date'] - join_df['newCases_startDate']

# check df after addition of the new column
display(join_df)

,location,primary_key_reaction,iso_code,minDate,maxDate,maxValue,changeGovResp,ramp_up_duration,population,population_density,...,newCases_startDate,CaseVsResp_Interval,AvgMaxGovResp_StartApr1,MaxNewCases_date,MaxNewCases_value,StartToMaxNewCases_Interval,MaxNewDeaths_date,MaxNewDeaths_value,MaxNewCasesToMaxNewDeaths_Interval,FirstNewCaseToMaxNewDeaths
0,Afghanistan,AFG2020-08-31,AFG,2020-03-01,2020-04-12,64.74,50.74,42 days,38928341.0,54.422,...,2020-02-25,-5 days,60.578889,2020-05-16,1063.0,76 days,2020-07-07,56.0,52 days,133 days
1,Albania,ALB2020-08-31,ALB,2020-03-09,2020-05-26,81.41,67.41,78 days,2877800.0,104.871,...,2020-03-09,0 days,68.489542,2020-08-25,178.0,169 days,2020-07-26,6.0,-30 days,139 days
2,Algeria,DZA2020-08-31,DZA,2020-03-12,2020-08-08,78.85,64.85,149 days,43851043.0,17.348,...,2020-02-26,-15 days,66.171046,2020-07-25,675.0,135 days,2020-04-04,42.0,-112 days,38 days
3,Angola,AGO2020-08-31,AGO,2020-03-24,2020-04-09,75.64,61.64,16 days,32866268.0,23.890,...,2020-03-22,-2 days,67.044379,2020-08-06,180.0,135 days,2020-07-30,6.0,-7 days,130 days
4,Argentina,ARG2020-08-31,ARG,2020-03-04,2020-03-25,91.03,77.03,21 days,45195777.0,16.177,...,2020-03-04,0 days,85.190196,2020-08-30,11730.0,179 days,2020-08-26,323.0,-4 days,175 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,Venezuela,VEN2020-08-31,VEN,2020-03-15,2020-06-22,75.64,61.64,99 days,28435943.0,36.253,...,2020-03-15,0 days,72.385621,2020-08-12,2133.0,150 days,2020-08-30,17.0,18 days,168 days
160,Vietnam,VNM2020-08-31,VNM,2020-01-29,2020-04-09,85.90,71.90,71 days,97338583.0,308.127,...,2020-01-24,-5 days,67.005033,2020-07-31,50.0,184 days,2020-08-12,4.0,12 days,201 days
161,Yemen,YEM2020-08-31,YEM,2020-04-10,2020-05-01,40.38,26.38,21 days,29825968.0,53.508,...,2020-04-10,0 days,32.003750,2020-06-16,116.0,67 days,2020-07-13,52.0,27 days,94 days
162,Zambia,ZMB2020-08-31,ZMB,2020-03-19,2020-05-02,63.14,49.14,44 days,18383956.0,22.995,...,2020-03-19,0 days,48.770523,2020-07-18,527.0,121 days,2020-07-15,40.0,-3 days,118 days
163,Zimbabwe,ZWE2020-08-31,ZWE,2020-03-21,2020-04-09,71.15,57.15,19 days,14862927.0,42.729,...,2020-03-21,0 days,66.137255,2020-08-02,490.0,134 days,2020-08-13,18.0,11 days,145 days

## Find the date 3 months from the date of the first case for each country
assume 1 month = 30 days

In [24]:
join_df['3mth_date'] = join_df['newCases_startDate'] + timedelta(days = 30)

# check df and dtypes
display(join_df)
join_df.dtypes

,location,primary_key_reaction,iso_code,minDate,maxDate,maxValue,changeGovResp,ramp_up_duration,population,population_density,...,CaseVsResp_Interval,AvgMaxGovResp_StartApr1,MaxNewCases_date,MaxNewCases_value,StartToMaxNewCases_Interval,MaxNewDeaths_date,MaxNewDeaths_value,MaxNewCasesToMaxNewDeaths_Interval,FirstNewCaseToMaxNewDeaths,3mth_date
0,Afghanistan,AFG2020-08-31,AFG,2020-03-01,2020-04-12,64.74,50.74,42 days,38928341.0,54.422,...,-5 days,60.578889,2020-05-16,1063.0,76 days,2020-07-07,56.0,52 days,133 days,2020-03-26
1,Albania,ALB2020-08-31,ALB,2020-03-09,2020-05-26,81.41,67.41,78 days,2877800.0,104.871,...,0 days,68.489542,2020-08-25,178.0,169 days,2020-07-26,6.0,-30 days,139 days,2020-04-08
2,Algeria,DZA2020-08-31,DZA,2020-03-12,2020-08-08,78.85,64.85,149 days,43851043.0,17.348,...,-15 days,66.171046,2020-07-25,675.0,135 days,2020-04-04,42.0,-112 days,38 days,2020-03-27
3,Angola,AGO2020-08-31,AGO,2020-03-24,2020-04-09,75.64,61.64,16 days,32866268.0,23.890,...,-2 days,67.044379,2020-08-06,180.0,135 days,2020-07-30,6.0,-7 days,130 days,2020-04-21
4,Argentina,ARG2020-08-31,ARG,2020-03-04,2020-03-25,91.03,77.03,21 days,45195777.0,16.177,...,0 days,85.190196,2020-08-30,11730.0,179 days,2020-08-26,323.0,-4 days,175 days,2020-04-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,Venezuela,VEN2020-08-31,VEN,2020-03-15,2020-06-22,75.64,61.64,99 days,28435943.0,36.253,...,0 days,72.385621,2020-08-12,2133.0,150 days,2020-08-30,17.0,18 days,168 days,2020-04-14
160,Vietnam,VNM2020-08-31,VNM,2020-01-29,2020-04-09,85.90,71.90,71 days,97338583.0,308.127,...,-5 days,67.005033,2020-07-31,50.0,184 days,2020-08-12,4.0,12 days,201 days,2020-02-23
161,Yemen,YEM2020-08-31,YEM,2020-04-10,2020-05-01,40.38,26.38,21 days,29825968.0,53.508,...,0 days,32.003750,2020-06-16,116.0,67 days,2020-07-13,52.0,27 days,94 days,2020-05-10
162,Zambia,ZMB2020-08-31,ZMB,2020-03-19,2020-05-02,63.14,49.14,44 days,18383956.0,22.995,...,0 days,48.770523,2020-07-18,527.0,121 days,2020-07-15,40.0,-3 days,118 days,2020-04-18
163,Zimbabwe,ZWE2020-08-31,ZWE,2020-03-21,2020-04-09,71.15,57.15,19 days,14862927.0,42.729,...,0 days,66.137255,2020-08-02,490.0,134 days,2020-08-13,18.0,11 days,145 days,2020-04-20

location                                       object
primary_key_reaction                           object
iso_code                                       object
minDate                                datetime64[ns]
maxDate                                datetime64[ns]
maxValue                                      float64
changeGovResp                                 float64
ramp_up_duration                      timedelta64[ns]
population                                    float64
population_density                            float64
median_age                                    float64
newCases_startDate                     datetime64[ns]
CaseVsResp_Interval                   timedelta64[ns]
AvgMaxGovResp_StartApr1                       float64
MaxNewCases_date                       datetime64[ns]
MaxNewCases_value                             float64
StartToMaxNewCases_Interval           timedelta64[ns]
MaxNewDeaths_date                      datetime64[ns]
MaxNewDeaths_value                            float64
MaxNewCasesToMaxNewDeaths_Interval    timedelta64[ns]
FirstNewCaseToMaxNewDeaths            timedelta64[ns]
3mth_date                              datetime64[ns]
dtype: object

## Find max. new cases, & total cases and total deaths 3 months (MO) after first case for each country

In [25]:
# series of dates 3 MO after the first case for each country
date3mnth = join_df['3mth_date']
date3mnth

0     2020-03-26
1     2020-04-08
2     2020-03-27
3     2020-04-21
4     2020-04-03
         ...
159   2020-04-14
160   2020-02-23
161   2020-05-10
162   2020-04-18
163   2020-04-20
Name: 3mth_date, Length: 164, dtype: datetime64[ns]

In [26]:
# convert "date_updated" in merged_covid to datetime
merged_covid['date_updated'] = pd.to_datetime(merged_covid['date_updated'])
merged_covid.dtypes

primary_key_reaction                            object
date_updated                            datetime64[ns]
iso_code                                        object
continent                                       object
location                                        object
population                                     float64
population_density                             float64
median_age                                     float64
new_cases                                      float64
percentage_of_Pop_New_Cases                    float64
new_deaths                                     float64
percentage_of_Pop_New_Deaths                   float64
new_tests                                      float64
percentage_of_Pop_New_Tests                    float64
total_cases_updated                            float64
percentage_of_Pop_Total_Cases                  float64
total_deaths_updated                           float64
percentage_of_Pop_Total_Deaths                 float64
total_tests_updated                            float64
percentage_of_Pop_Total_Tests                  float64
primary_key_response                            object
StringencyIndex_updated                        float64
percentage_change_stringency                   float64
StringencyLegacyIndex_updated                  float64
GovernmentResponseIndex_updated                float64
percentage_change_GovernmentResponse           float64
ContainmentHealthIndex_updated                 float64
percentage_change_ContainmentHealth            float64
EconomicSupportIndex_updated                   float64
percentage_change_EconomicSupport              float64
dtype: object

In [27]:
# for loop
countries3mnth_array = []

for i in range(0,164):
    country = countries[i]
    date3mnth_country = date3mnth[i]
    country3mnth_dict = {}
    
    countryLoc = merged_covid.loc[merged_covid['location'] == country]
    maxNewCases_3mnth_df = countryLoc[(countryLoc['date_updated'] >= date3mnth_country)]
    
    if maxNewCases_3mnth_df.empty == False:
        newCases = maxNewCases_3mnth_df.iloc[0,8]
        totCases = maxNewCases_3mnth_df.iloc[0,14]
        newDeaths = maxNewCases_3mnth_df.iloc[0,10] 
        totDeaths = maxNewCases_3mnth_df.iloc[0,16] 
        
        country3mnth_dict['country'] = country 
        country3mnth_dict['newCases'] = newCases
        country3mnth_dict['totCases'] = totCases
        country3mnth_dict['newDeaths'] = newDeaths
        country3mnth_dict['totDeaths'] = totDeaths

        countries3mnth_array.append(country3mnth_dict)

countries3mnth_array

[{'country': 'Afghanistan',
  'newCases': 33.0,
  'totCases': 75.0,
  'newDeaths': 0.0,
  'totDeaths': 1.0},
 {'country': 'Albania',
  'newCases': 6.0,
  'totCases': 383.0,
  'newDeaths': 0.0,
  'totDeaths': 22.0},
 {'country': 'Algeria',
  'newCases': 65.0,
  'totCases': 367.0,
  'newDeaths': 4.0,
  'totDeaths': 25.0},
 {'country': 'Angola',
  'newCases': 0.0,
  'totCases': 24.0,
  'newDeaths': 0.0,
  'totDeaths': 2.0},
 {'country': 'Argentina',
  'newCases': 0.0,
  'totCases': 1133.0,
  'newDeaths': 3.0,
  'totDeaths': 34.0},
 {'country': 'Aruba',
  'newCases': 6.0,
  'totCases': 92.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Australia',
  'newCases': 0.0,
  'totCases': 22.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Austria',
  'newCases': 1141.0,
  'totCases': 7029.0,
  'newDeaths': 18.0,
  'totDeaths': 52.0},
 {'country': 'Azerbaijan',
  'newCases': 27.0,
  'totCases': 209.0,
  'newDeaths': 0.0,
  'totDeaths': 4.0},
 {'country': 'Bahrain',
  'newCases': 51.0,
  'totCases': 390.0,
  'newDeaths': 1.0,
  'totDeaths': 3.0},
 {'country': 'Bangladesh',
  'newCases': 41.0,
  'totCases': 164.0,
  'newDeaths': 5.0,
  'totDeaths': 17.0},
 {'country': 'Barbados',
  'newCases': 0.0,
  'totCases': 75.0,
  'newDeaths': 0.0,
  'totDeaths': 5.0},
 {'country': 'Belarus',
  'newCases': 0.0,
  'totCases': 94.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Belgium',
  'newCases': 53.0,
  'totCases': 125.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Belize',
  'newCases': 0.0,
  'totCases': 18.0,
  'newDeaths': 0.0,
  'totDeaths': 2.0},
 {'country': 'Benin',
  'newCases': 0.0,
  'totCases': 35.0,
  'newDeaths': 0.0,
  'totDeaths': 1.0},
 {'country': 'Bhutan',
  'newCases': 0.0,
  'totCases': 5.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Bolivia',
  'newCases': 8.0,
  'totCases': 276.0,
  'newDeaths': 1.0,
  'totDeaths': 20.0},
 {'country': 'Bosnia and Herzegovina',
  'newCases': 46.0,
  'totCases': 632.0,
  'newDeaths': 3.0,
  'totDeaths': 21.0},
 {'country': 'Botswana',
  'newCases': 0.0,
  'totCases': 23.0,
  'newDeaths': 0.0,
  'totDeaths': 1.0},
 {'country': 'Brazil',
  'newCases': 482.0,
  'totCases': 2915.0,
  'newDeaths': 20.0,
  'totDeaths': 77.0},
 {'country': 'Brunei',
  'newCases': 0.0,
  'totCases': 135.0,
  'newDeaths': 0.0,
  'totDeaths': 1.0},
 {'country': 'Bulgaria',
  'newCases': 18.0,
  'totCases': 549.0,
  'newDeaths': 2.0,
  'totDeaths': 22.0},
 {'country': 'Burkina Faso',
  'newCases': 29.0,
  'totCases': 443.0,
  'newDeaths': 1.0,
  'totDeaths': 24.0},
 {'country': 'Burundi',
  'newCases': 0.0,
  'totCases': 15.0,
  'newDeaths': 0.0,
  'totDeaths': 1.0},
 {'country': 'Cambodia',
  'newCases': 0.0,
  'totCases': 1.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Cameroon',
  'newCases': 95.0,
  'totCases': 650.0,
  'newDeaths': 0.0,
  'totDeaths': 9.0},
 {'country': 'Canada',
  'newCases': 2.0,
  'totCases': 11.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Cape Verde',
  'newCases': 3.0,
  'totCases': 61.0,
  'newDeaths': 0.0,
  'totDeaths': 1.0},
 {'country': 'Central African Republic',
  'newCases': 0.0,
  'totCases': 11.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Chad',
  'newCases': 0.0,
  'totCases': 33.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Chile',
  'newCases': 373.0,
  'totCases': 3404.0,
  'newDeaths': 2.0,
  'totDeaths': 18.0},
 {'country': 'China',
  'newCases': 2590.0,
  'totCases': 14399.0,
  'newDeaths': 45.0,
  'totDeaths': 304.0},
 {'country': 'Colombia',
  'newCases': 79.0,
  'totCases': 1485.0,
  'newDeaths': 3.0,
  'totDeaths': 35.0},
 {'country': 'Congo',
  'newCases': 4.0,
  'totCases': 74.0,
  'newDeaths': 0.0,
  'totDeaths': 5.0},
 {'country': 'Costa Rica',
  'newCases': 19.0,
  'totCases': 454.0,
  'newDeaths': 0.0,
  'totDeaths': 2.0},
 {'country': "Cote d'Ivoire",
  'newCases': 36.0,
  'totCases': 480.0,
  'newDeaths': 0.0,
  'totDeaths': 3.0},
 {'country': 'Croatia',
  'newCases': 77.0,
  'totCases': 495.0,
  'newDeaths': 1.0,
  'totDeaths': 2.0},
 {'country': 'Cuba',
  'newCases': 49.0,
  'totCases': 564.0,
  'newDeaths': 0.0,
  'totDeaths': 15.0},
 {'country': 'Cyprus',
  'newCases': 32.0,
  'totCases': 526.0,
  'newDeaths': 0.0,
  'totDeaths': 9.0},
 {'country': 'Czech Republic',
  'newCases': 306.0,
  'totCases': 3308.0,
  'newDeaths': 7.0,
  'totDeaths': 31.0},
 {'country': 'Democratic Republic of Congo',
  'newCases': 32.0,
  'totCases': 215.0,
  'newDeaths': 0.0,
  'totDeaths': 20.0},
 {'country': 'Denmark',
  'newCases': 169.0,
  'totCases': 2046.0,
  'newDeaths': 11.0,
  'totDeaths': 52.0},
 {'country': 'Djibouti',
  'newCases': 141.0,
  'totCases': 732.0,
  'newDeaths': 0.0,
  'totDeaths': 2.0},
 {'country': 'Dominican Republic',
  'newCases': 208.0,
  'totCases': 1109.0,
  'newDeaths': 9.0,
  'totDeaths': 51.0},
 {'country': 'Ecuador',
  'newCases': 76.0,
  'totCases': 1966.0,
  'newDeaths': 4.0,
  'totDeaths': 62.0},
 {'country': 'Egypt',
  'newCases': 17.0,
  'totCases': 110.0,
  'newDeaths': 0.0,
  'totDeaths': 2.0},
 {'country': 'El Salvador',
  'newCases': 13.0,
  'totCases': 177.0,
  'newDeaths': 1.0,
  'totDeaths': 7.0},
 {'country': 'Eritrea',
  'newCases': 0.0,
  'totCases': 39.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Estonia',
  'newCases': 65.0,
  'totCases': 640.0,
  'newDeaths': 0.0,
  'totDeaths': 1.0},
 {'country': 'Ethiopia',
  'newCases': 2.0,
  'totCases': 71.0,
  'newDeaths': 0.0,
  'totDeaths': 3.0},
 {'country': 'Fiji',
  'newCases': 0.0,
  'totCases': 17.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Finland',
  'newCases': 1.0,
  'totCases': 3.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'France',
  'newCases': 0.0,
  'totCases': 12.0,
  'newDeaths': 0.0,
  'totDeaths': 1.0},
 {'country': 'Gabon',
  'newCases': 3.0,
  'totCases': 49.0,
  'newDeaths': 0.0,
  'totDeaths': 1.0},
 {'country': 'Gambia',
  'newCases': 0.0,
  'totCases': 9.0,
  'newDeaths': 0.0,
  'totDeaths': 1.0},
 {'country': 'Georgia',
  'newCases': 2.0,
  'totCases': 81.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Germany',
  'newCases': 4.0,
  'totCases': 21.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Ghana',
  'newCases': 30.0,
  'totCases': 408.0,
  'newDeaths': 2.0,
  'totDeaths': 8.0},
 {'country': 'Greece',
  'newCases': 74.0,
  'totCases': 966.0,
  'newDeaths': 2.0,
  'totDeaths': 28.0},
 {'country': 'Guam',
  'newCases': 1.0,
  'totCases': 136.0,
  'newDeaths': 0.0,
  'totDeaths': 5.0},
 {'country': 'Guatemala',
  'newCases': 11.0,
  'totCases': 167.0,
  'newDeaths': 0.0,
  'totDeaths': 5.0},
 {'country': 'Guinea',
  'newCases': 0.0,
  'totCases': 250.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Guyana',
  'newCases': 5.0,
  'totCases': 45.0,
  'newDeaths': 0.0,
  'totDeaths': 6.0},
 {'country': 'Haiti',
  'newCases': 0.0,
  'totCases': 44.0,
  'newDeaths': 0.0,
  'totDeaths': 3.0},
 {'country': 'Honduras',
  'newCases': 10.0,
  'totCases': 392.0,
  'newDeaths': 1.0,
  'totDeaths': 24.0},
 {'country': 'Hong Kong',
  'newCases': 0.0,
  'totCases': 0.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Hungary',
  'newCases': 55.0,
  'totCases': 678.0,
  'newDeaths': 6.0,
  'totDeaths': 32.0},
 {'country': 'Iceland',
  'newCases': 57.0,
  'totCases': 1020.0,
  'newDeaths': 0.0,
  'totDeaths': 2.0},
 {'country': 'India',
  'newCases': 0.0,
  'totCases': 3.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Indonesia',
  'newCases': 114.0,
  'totCases': 1528.0,
  'newDeaths': 14.0,
  'totDeaths': 136.0},
 {'country': 'Iran',
  'newCases': 1237.0,
  'totCases': 19644.0,
  'newDeaths': 149.0,
  'totDeaths': 1433.0},
 {'country': 'Iraq',
  'newCases': 30.0,
  'totCases': 346.0,
  'newDeaths': 2.0,
  'totDeaths': 29.0},
 {'country': 'Ireland',
  'newCases': 295.0,
  'totCases': 2910.0,
  'newDeaths': 8.0,
  'totDeaths': 54.0},
 {'country': 'Israel',
  'newCases': 188.0,
  'totCases': 1071.0,
  'newDeaths': 0.0,
  'totDeaths': 1.0},
 {'country': 'Italy',
  'newCases': 240.0,
  'totCases': 1128.0,
  'newDeaths': 8.0,
  'totDeaths': 29.0},
 {'country': 'Jamaica',
  'newCases': 2.0,
  'totCases': 65.0,
  'newDeaths': 0.0,
  'totDeaths': 4.0},
 {'country': 'Japan',
  'newCases': 1.0,
  'totCases': 30.0,
  'newDeaths': 0.0,
  'totDeaths': 1.0},
 {'country': 'Jordan',
  'newCases': 4.0,
  'totCases': 278.0,
  'newDeaths': 0.0,
  'totDeaths': 5.0},
 {'country': 'Kazakhstan',
  'newCases': 218.0,
  'totCases': 1179.0,
  'newDeaths': 4.0,
  'totDeaths': 14.0},
 {'country': 'Kenya',
  'newCases': 6.0,
  'totCases': 197.0,
  'newDeaths': 1.0,
  'totDeaths': 8.0},
 {'country': 'Kuwait',
  'newCases': 2.0,
  'totCases': 191.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Kyrgyzstan',
  'newCases': 17.0,
  'totCases': 506.0,
  'newDeaths': 0.0,
  'totDeaths': 5.0},
 {'country': 'Laos',
  'newCases': 0.0,
  'totCases': 19.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Latvia',
  'newCases': 48.0,
  'totCases': 446.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Lebanon',
  'newCases': 18.0,
  'totCases': 248.0,
  'newDeaths': 0.0,
  'totDeaths': 4.0},
 {'country': 'Lesotho',
  'newCases': 0.0,
  'totCases': 4.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Liberia',
  'newCases': 0.0,
  'totCases': 59.0,
  'newDeaths': 0.0,
  'totDeaths': 6.0},
 {'country': 'Libya',
  'newCases': 1.0,
  'totCases': 60.0,
  'newDeaths': 1.0,
  'totDeaths': 2.0},
 {'country': 'Lithuania',
  'newCases': 36.0,
  'totCases': 394.0,
  'newDeaths': 2.0,
  'totDeaths': 7.0},
 {'country': 'Luxembourg',
  'newCases': 38.0,
  'totCases': 1988.0,
  'newDeaths': 1.0,
  'totDeaths': 22.0},
 {'country': 'Madagascar',
  'newCases': 4.0,
  'totCases': 121.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Malawi',
  'newCases': 1.0,
  'totCases': 38.0,
  'newDeaths': 0.0,
  'totDeaths': 3.0},
 {'country': 'Malaysia',
  'newCases': 0.0,
  'totCases': 22.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Mali',
  'newCases': 16.0,
  'totCases': 325.0,
  'newDeaths': 0.0,
  'totDeaths': 21.0},
 {'country': 'Mauritania',
  'newCases': 0.0,
  'totCases': 7.0,
  'newDeaths': 0.0,
  'totDeaths': 1.0},
 {'country': 'Mauritius',
  'newCases': 1.0,
  'totCases': 325.0,
  'newDeaths': 0.0,
  'totDeaths': 9.0},
 {'country': 'Mexico',
  'newCases': 145.0,
  'totCases': 993.0,
  'newDeaths': 4.0,
  'totDeaths': 20.0},
 {'country': 'Moldova',
  'newCases': 101.0,
  'totCases': 965.0,
  'newDeaths': 4.0,
  'totDeaths': 19.0},
 {'country': 'Mongolia',
  'newCases': 1.0,
  'totCases': 16.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Morocco',
  'newCases': 37.0,
  'totCases': 654.0,
  'newDeaths': 3.0,
  'totDeaths': 39.0},
 {'country': 'Mozambique',
  'newCases': 0.0,
  'totCases': 39.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Myanmar',
  'newCases': 6.0,
  'totCases': 127.0,
  'newDeaths': 0.0,
  'totDeaths': 5.0},
 {'country': 'Namibia',
  'newCases': 0.0,
  'totCases': 16.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Nepal',
  'newCases': 0.0,
  'totCases': 1.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Netherlands',
  'newCases': 1159.0,
  'totCases': 9762.0,
  'newDeaths': 93.0,
  'totDeaths': 639.0},
 {'country': 'New Zealand',
  'newCases': 60.0,
  'totCases': 476.0,
  'newDeaths': 1.0,
  'totDeaths': 1.0},
 {'country': 'Nicaragua',
  'newCases': 0.0,
  'totCases': 9.0,
  'newDeaths': 0.0,
  'totDeaths': 1.0},
 {'country': 'Niger',
  'newCases': 9.0,
  'totCases': 648.0,
  'newDeaths': 1.0,
  'totDeaths': 20.0},
 {'country': 'Nigeria',
  'newCases': 16.0,
  'totCases': 97.0,
  'newDeaths': 0.0,
  'totDeaths': 1.0},
 {'country': 'Norway',
  'newCases': 425.0,
  'totCases': 3581.0,
  'newDeaths': 2.0,
  'totDeaths': 16.0},
 {'country': 'Oman',
  'newCases': 15.0,
  'totCases': 99.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Pakistan',
  'newCases': 0.0,
  'totCases': 1197.0,
  'newDeaths': 0.0,
  'totDeaths': 9.0},
 {'country': 'Palestine',
  'newCases': 0.0,
  'totCases': 155.0,
  'newDeaths': 0.0,
  'totDeaths': 1.0},
 {'country': 'Panama',
  'newCases': 279.0,
  'totCases': 2528.0,
  'newDeaths': 4.0,
  'totDeaths': 63.0},
 {'country': 'Papua New Guinea',
  'newCases': 0.0,
  'totCases': 7.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Paraguay',
  'newCases': 0.0,
  'totCases': 113.0,
  'newDeaths': 0.0,
  'totDeaths': 5.0},
 {'country': 'Peru',
  'newCases': 535.0,
  'totCases': 2281.0,
  'newDeaths': 10.0,
  'totDeaths': 83.0},
 {'country': 'Philippines',
  'newCases': 0.0,
  'totCases': 3.0,
  'newDeaths': 0.0,
  'totDeaths': 1.0},
 {'country': 'Poland',
  'newCases': 392.0,
  'totCases': 2946.0,
  'newDeaths': 14.0,
  'totDeaths': 57.0},
 {'country': 'Portugal',
  'newCases': 808.0,
  'totCases': 8251.0,
  'newDeaths': 27.0,
  'totDeaths': 187.0},
 {'country': 'Puerto Rico',
  'newCases': 64.0,
  'totCases': 1371.0,
  'newDeaths': 1.0,
  'totDeaths': 84.0},
 {'country': 'Qatar',
  'newCases': 59.0,
  'totCases': 693.0,
  'newDeaths': 0.0,
  'totDeaths': 1.0},
 {'country': 'Romania',
  'newCases': 263.0,
  'totCases': 1292.0,
  'newDeaths': 7.0,
  'totDeaths': 24.0},
 {'country': 'Russia',
  'newCases': 0.0,
  'totCases': 2.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Rwanda',
  'newCases': 1.0,
  'totCases': 127.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Saudi Arabia',
  'newCases': 157.0,
  'totCases': 1720.0,
  'newDeaths': 6.0,
  'totDeaths': 16.0},
 {'country': 'Senegal',
  'newCases': 15.0,
  'totCases': 190.0,
  'newDeaths': 1.0,
  'totDeaths': 1.0},
 {'country': 'Serbia',
  'newCases': 284.0,
  'totCases': 1908.0,
  'newDeaths': 7.0,
  'totDeaths': 51.0},
 {'country': 'Seychelles',
  'newCases': 0.0,
  'totCases': 10.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Sierra Leone',
  'newCases': 8.0,
  'totCases': 124.0,
  'newDeaths': 3.0,
  'totDeaths': 7.0},
 {'country': 'Singapore',
  'newCases': 3.0,
  'totCases': 89.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Slovakia',
  'newCases': 14.0,
  'totCases': 485.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Slovenia',
  'newCases': 37.0,
  'totCases': 934.0,
  'newDeaths': 4.0,
  'totDeaths': 20.0},
 {'country': 'Somalia',
  'newCases': 20.0,
  'totCases': 80.0,
  'newDeaths': 3.0,
  'totDeaths': 5.0},
 {'country': 'South Africa',
  'newCases': 80.0,
  'totCases': 1585.0,
  'newDeaths': 2.0,
  'totDeaths': 9.0},
 {'country': 'South Korea',
  'newCases': 15.0,
  'totCases': 46.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Spain',
  'newCases': 54.0,
  'totCases': 136.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Sri Lanka',
  'newCases': 0.0,
  'totCases': 1.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Sudan',
  'newCases': 0.0,
  'totCases': 19.0,
  'newDeaths': 0.0,
  'totDeaths': 2.0},
 {'country': 'Suriname',
  'newCases': 0.0,
  'totCases': 10.0,
  'newDeaths': 0.0,
  'totDeaths': 1.0},
 {'country': 'Swaziland',
  'newCases': 1.0,
  'totCases': 15.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Sweden',
  'newCases': 3.0,
  'totCases': 14.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Switzerland',
  'newCases': 1000.0,
  'totCases': 10714.0,
  'newDeaths': 58.0,
  'totDeaths': 161.0},
 {'country': 'Tajikistan',
  'newCases': 244.0,
  'totCases': 3807.0,
  'newDeaths': 0.0,
  'totDeaths': 47.0},
 {'country': 'Tanzania',
  'newCases': 35.0,
  'totCases': 88.0,
  'newDeaths': 1.0,
  'totDeaths': 4.0},
 {'country': 'Thailand',
  'newCases': 1.0,
  'totCases': 33.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Timor',
  'newCases': 3.0,
  'totCases': 22.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Togo',
  'newCases': 3.0,
  'totCases': 44.0,
  'newDeaths': 0.0,
  'totDeaths': 3.0},
 {'country': 'Trinidad and Tobago',
  'newCases': 3.0,
  'totCases': 112.0,
  'newDeaths': 0.0,
  'totDeaths': 8.0},
 {'country': 'Tunisia',
  'newCases': 32.0,
  'totCases': 394.0,
  'newDeaths': 1.0,
  'totDeaths': 10.0},
 {'country': 'Turkey',
  'newCases': 4747.0,
  'totCases': 47029.0,
  'newDeaths': 98.0,
  'totDeaths': 1006.0},
 {'country': 'Uganda',
  'newCases': 1.0,
  'totCases': 56.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Ukraine',
  'newCases': 103.0,
  'totCases': 897.0,
  'newDeaths': 2.0,
  'totDeaths': 22.0},
 {'country': 'United Arab Emirates',
  'newCases': 0.0,
  'totCases': 13.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'United Kingdom',
  'newCases': 5.0,
  'totCases': 47.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'United States',
  'newCases': 0.0,
  'totCases': 15.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Uruguay',
  'newCases': 7.0,
  'totCases': 472.0,
  'newDeaths': 0.0,
  'totDeaths': 8.0},
 {'country': 'Uzbekistan',
  'newCases': 167.0,
  'totCases': 1165.0,
  'newDeaths': 0.0,
  'totDeaths': 4.0},
 {'country': 'Venezuela',
  'newCases': 8.0,
  'totCases': 189.0,
  'newDeaths': 0.0,
  'totDeaths': 9.0},
 {'country': 'Vietnam',
  'newCases': 0.0,
  'totCases': 16.0,
  'newDeaths': 0.0,
  'totDeaths': 0.0},
 {'country': 'Yemen',
  'newCases': 0.0,
  'totCases': 34.0,
  'newDeaths': 0.0,
  'totDeaths': 7.0},
 {'country': 'Zambia',
  'newCases': 4.0,
  'totCases': 52.0,
  'newDeaths': 0.0,
  'totDeaths': 2.0},
 {'country': 'Zimbabwe',
  'newCases': 0.0,
  'totCases': 25.0,
  'newDeaths': 0.0,
  'totDeaths': 3.0}]

In [28]:
# create 3 mnths later df:
# index = length of array
# columns = country, newCases, totCases, newDeaths, totDeaths

# check there are 164 values corresponding to 164 countries
print(len(countries3mnth_array))

countries = []
newCases_list = []
totCases_list = []
newDeaths_list = []
totDeaths_list = []

for item in countries3mnth_array:
    country = item['country']
    countries.append(country)
    
    newCases = item['newCases']
    newCases_list.append(newCases)
    
    totCases = item['totCases']
    totCases_list.append(totCases)
    
    newDeaths = item['newDeaths']
    newDeaths_list.append(newDeaths)
    
    totDeaths = item['totDeaths']
    totDeaths_list.append(totDeaths)
    
# print to preview each list
# print(countries)
# print(newCases_list)
# print(totCases_list)
# print(newDeaths_list)
# print(totDeaths_list)

df_dict = {"location": countries,
           "newCases_3mnth": newCases_list,
           "totCases_3mnth": totCases_list,
           "newDeaths_3mnth": newDeaths_list,
           "totDeaths_3mnth": totDeaths_list
          }

indexDF = np.array(range(0,164))

# make df
df_3mnth = pd.DataFrame.from_dict(df_dict)

# preview created df
df_3mnth

164

,location,newCases_3mnth,totCases_3mnth,newDeaths_3mnth,totDeaths_3mnth
0,Afghanistan,33.0,75.0,0.0,1.0
1,Albania,6.0,383.0,0.0,22.0
2,Algeria,65.0,367.0,4.0,25.0
3,Angola,0.0,24.0,0.0,2.0
4,Argentina,0.0,1133.0,3.0,34.0
...,...,...,...,...,...
159,Venezuela,8.0,189.0,0.0,9.0
160,Vietnam,0.0,16.0,0.0,0.0
161,Yemen,0.0,34.0,0.0,7.0
162,Zambia,4.0,52.0,0.0,2.0
163,Zimbabwe,0.0,25.0,0.0,3.0

## Join df with 3 mnth data to previous df

In [29]:
join3mnth = join_df.merge(df_3mnth, on='location', how='inner')
join3mnth

,location,primary_key_reaction,iso_code,minDate,maxDate,maxValue,changeGovResp,ramp_up_duration,population,population_density,...,StartToMaxNewCases_Interval,MaxNewDeaths_date,MaxNewDeaths_value,MaxNewCasesToMaxNewDeaths_Interval,FirstNewCaseToMaxNewDeaths,3mth_date,newCases_3mnth,totCases_3mnth,newDeaths_3mnth,totDeaths_3mnth
0,Afghanistan,AFG2020-08-31,AFG,2020-03-01,2020-04-12,64.74,50.74,42 days,38928341.0,54.422,...,76 days,2020-07-07,56.0,52 days,133 days,2020-03-26,33.0,75.0,0.0,1.0
1,Albania,ALB2020-08-31,ALB,2020-03-09,2020-05-26,81.41,67.41,78 days,2877800.0,104.871,...,169 days,2020-07-26,6.0,-30 days,139 days,2020-04-08,6.0,383.0,0.0,22.0
2,Algeria,DZA2020-08-31,DZA,2020-03-12,2020-08-08,78.85,64.85,149 days,43851043.0,17.348,...,135 days,2020-04-04,42.0,-112 days,38 days,2020-03-27,65.0,367.0,4.0,25.0
3,Angola,AGO2020-08-31,AGO,2020-03-24,2020-04-09,75.64,61.64,16 days,32866268.0,23.890,...,135 days,2020-07-30,6.0,-7 days,130 days,2020-04-21,0.0,24.0,0.0,2.0
4,Argentina,ARG2020-08-31,ARG,2020-03-04,2020-03-25,91.03,77.03,21 days,45195777.0,16.177,...,179 days,2020-08-26,323.0,-4 days,175 days,2020-04-03,0.0,1133.0,3.0,34.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,Venezuela,VEN2020-08-31,VEN,2020-03-15,2020-06-22,75.64,61.64,99 days,28435943.0,36.253,...,150 days,2020-08-30,17.0,18 days,168 days,2020-04-14,8.0,189.0,0.0,9.0
160,Vietnam,VNM2020-08-31,VNM,2020-01-29,2020-04-09,85.90,71.90,71 days,97338583.0,308.127,...,184 days,2020-08-12,4.0,12 days,201 days,2020-02-23,0.0,16.0,0.0,0.0
161,Yemen,YEM2020-08-31,YEM,2020-04-10,2020-05-01,40.38,26.38,21 days,29825968.0,53.508,...,67 days,2020-07-13,52.0,27 days,94 days,2020-05-10,0.0,34.0,0.0,7.0
162,Zambia,ZMB2020-08-31,ZMB,2020-03-19,2020-05-02,63.14,49.14,44 days,18383956.0,22.995,...,121 days,2020-07-15,40.0,-3 days,118 days,2020-04-18,4.0,52.0,0.0,2.0
163,Zimbabwe,ZWE2020-08-31,ZWE,2020-03-21,2020-04-09,71.15,57.15,19 days,14862927.0,42.729,...,134 days,2020-08-13,18.0,11 days,145 days,2020-04-20,0.0,25.0,0.0,3.0

## Include gdp in df

In [30]:
# preview gdp df
display(gdp)
print(list(gdp.columns))

gdp = gdp.sort_values(['location','date'])

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy
0,ABW,North America,Aruba,2020-03-13,2.0,2.0,NaN,0.0,0.0,NaN,...,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29
1,ABW,North America,Aruba,2020-03-19,NaN,NaN,0.286,NaN,NaN,0.0,...,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29
2,ABW,North America,Aruba,2020-03-20,4.0,2.0,0.286,0.0,0.0,0.0,...,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29
3,ABW,North America,Aruba,2020-03-21,NaN,NaN,0.286,NaN,NaN,0.0,...,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29
4,ABW,North America,Aruba,2020-03-22,NaN,NaN,0.286,NaN,NaN,0.0,...,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40743,NaN,NaN,International,2020-08-27,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40744,NaN,NaN,International,2020-08-28,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40745,NaN,NaN,International,2020-08-29,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40746,NaN,NaN,International,2020-08-30,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40747,NaN,NaN,International,2020-08-31,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases', 'new_cases_smoothed', 'total_deaths', 'new_deaths', 'new_deaths_smoothed', 'total_cases_per_million', 'new_cases_per_million', 'new_cases_smoothed_per_million', 'total_deaths_per_million', 'new_deaths_per_million', 'new_deaths_smoothed_per_million', 'new_tests', 'total_tests', 'total_tests_per_thousand', 'new_tests_per_thousand', 'new_tests_smoothed', 'new_tests_smoothed_per_thousand', 'tests_per_case', 'positive_rate', 'tests_units', 'stringency_index', 'population', 'population_density', 'median_age', 'aged_65_older', 'aged_70_older', 'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers', 'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand', 'life_expectancy']

In [31]:
print(gdp['gdp_per_capita'].nunique())

# drop null values for gdp
gdp.dropna(inplace=True)
gdp_grp = gdp.groupby('location').max()
gdp_grp = gdp_grp.reset_index()

# join gdp to previous df
gdpToJoin = gdp_grp[['location','gdp_per_capita']]
join3mnthGDP = join3mnth.merge(gdpToJoin, on='location', how='left')

# previous list of columns for the df
list(join3mnthGDP.columns)

184

['location',
 'primary_key_reaction',
 'iso_code',
 'minDate',
 'maxDate',
 'maxValue',
 'changeGovResp',
 'ramp_up_duration',
 'population',
 'population_density',
 'median_age',
 'newCases_startDate',
 'CaseVsResp_Interval',
 'AvgMaxGovResp_StartApr1',
 'MaxNewCases_date',
 'MaxNewCases_value',
 'StartToMaxNewCases_Interval',
 'MaxNewDeaths_date',
 'MaxNewDeaths_value',
 'MaxNewCasesToMaxNewDeaths_Interval',
 'FirstNewCaseToMaxNewDeaths',
 '3mth_date',
 'newCases_3mnth',
 'totCases_3mnth',
 'newDeaths_3mnth',
 'totDeaths_3mnth',
 'gdp_per_capita']

## Include indices in the df

In [32]:
# preview the indices
display(string)
display(health)
display(econ)

        location  StringencyIndex_updated
0       Honduras                96.764052
1          Libya                93.838954
2      Guatemala                93.812288
3        Eritrea                93.520000
4    El Salvador                92.584510
..           ...                      ...
159        Japan                34.089150
160        Niger                32.968693
161      Burundi                26.869346
162    Nicaragua                13.435752
163      Belarus                12.944118

[164 rows x 2 columns]

        location  ContainmentHealthIndex_updated
0           Oman                       87.740784
1    El Salvador                       87.624902
2     Azerbaijan                       87.176405
3      Argentina                       87.041569
4       Honduras                       86.741634
..           ...                             ...
159        Niger                       34.553922
160     Tanzania                       32.317190
161      Burundi                       31.294248
162      Belarus                       27.170261
163    Nicaragua                       14.321111

[164 rows x 2 columns]

           location  EconomicSupportIndex_updated
0           Iceland                         100.0
1           Ireland                         100.0
2         Hong Kong                         100.0
3            Cyprus                         100.0
4    United Kingdom                         100.0
..              ...                           ...
159          Mexico                           0.0
160      Mozambique                           0.0
161        Tanzania                           0.0
162       Nicaragua                           0.0
163     Afghanistan                           0.0

[164 rows x 2 columns]

In [33]:
# merge dfs of all indices with previous df
mergeString = join3mnthGDP.merge(string, on='location', how='left')
mergeString
mergeHealth = mergeString.merge(health, on='location', how='left')
mergeHealth
mergeEcon = mergeHealth.merge(econ, on='location', how='left')

# check all dfs were merged properly
display(mergeEcon)
mergeEcon.columns.to_list()

,location,primary_key_reaction,iso_code,minDate,maxDate,maxValue,changeGovResp,ramp_up_duration,population,population_density,...,FirstNewCaseToMaxNewDeaths,3mth_date,newCases_3mnth,totCases_3mnth,newDeaths_3mnth,totDeaths_3mnth,gdp_per_capita,StringencyIndex_updated,ContainmentHealthIndex_updated,EconomicSupportIndex_updated
0,Afghanistan,AFG2020-08-31,AFG,2020-03-01,2020-04-12,64.74,50.74,42 days,38928341.0,54.422,...,133 days,2020-03-26,33.0,75.0,0.0,1.0,NaN,77.056601,71.595294,0.000000
1,Albania,ALB2020-08-31,ALB,2020-03-09,2020-05-26,81.41,67.41,78 days,2877800.0,104.871,...,139 days,2020-04-08,6.0,383.0,0.0,22.0,NaN,71.082157,69.281699,64.133987
2,Algeria,DZA2020-08-31,DZA,2020-03-12,2020-08-08,78.85,64.85,149 days,43851043.0,17.348,...,38 days,2020-03-27,65.0,367.0,4.0,25.0,NaN,77.349804,70.179869,44.117647
3,Angola,AGO2020-08-31,AGO,2020-03-24,2020-04-09,75.64,61.64,16 days,32866268.0,23.890,...,130 days,2020-04-21,0.0,24.0,0.0,2.0,NaN,79.376863,71.983987,39.869281
4,Argentina,ARG2020-08-31,ARG,2020-03-04,2020-03-25,91.03,77.03,21 days,45195777.0,16.177,...,175 days,2020-04-03,0.0,1133.0,3.0,34.0,NaN,91.496536,87.041569,75.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,Venezuela,VEN2020-08-31,VEN,2020-03-15,2020-06-22,75.64,61.64,99 days,28435943.0,36.253,...,168 days,2020-04-14,8.0,189.0,0.0,9.0,NaN,84.127516,76.455817,50.000000
160,Vietnam,VNM2020-08-31,VNM,2020-01-29,2020-04-09,85.90,71.90,71 days,97338583.0,308.127,...,201 days,2020-02-23,0.0,16.0,0.0,0.0,6171.884,68.959869,73.456863,31.535948
161,Yemen,YEM2020-08-31,YEM,2020-04-10,2020-05-01,40.38,26.38,21 days,29825968.0,53.508,...,94 days,2020-05-10,0.0,34.0,0.0,7.0,NaN,46.230000,37.827153,0.000000
162,Zambia,ZMB2020-08-31,ZMB,2020-03-19,2020-05-02,63.14,49.14,44 days,18383956.0,22.995,...,118 days,2020-04-18,4.0,52.0,0.0,2.0,NaN,50.076405,53.093987,25.000000
163,Zimbabwe,ZWE2020-08-31,ZWE,2020-03-21,2020-04-09,71.15,57.15,19 days,14862927.0,42.729,...,145 days,2020-04-20,0.0,25.0,0.0,3.0,1899.775,81.166471,73.826405,23.856209

['location',
 'primary_key_reaction',
 'iso_code',
 'minDate',
 'maxDate',
 'maxValue',
 'changeGovResp',
 'ramp_up_duration',
 'population',
 'population_density',
 'median_age',
 'newCases_startDate',
 'CaseVsResp_Interval',
 'AvgMaxGovResp_StartApr1',
 'MaxNewCases_date',
 'MaxNewCases_value',
 'StartToMaxNewCases_Interval',
 'MaxNewDeaths_date',
 'MaxNewDeaths_value',
 'MaxNewCasesToMaxNewDeaths_Interval',
 'FirstNewCaseToMaxNewDeaths',
 '3mth_date',
 'newCases_3mnth',
 'totCases_3mnth',
 'newDeaths_3mnth',
 'totDeaths_3mnth',
 'gdp_per_capita',
 'StringencyIndex_updated',
 'ContainmentHealthIndex_updated',
 'EconomicSupportIndex_updated']

## Include mobility in the previous df
Will use avg. mobility for each country over a 3-MO duration (from min. gov resp to 3 mnths after that)

In [34]:
# mobility (avg. mobility outdoors and indoors over the 3 MO)
# sort by country, then date
mobil.sort_values(by=['country','date'])
mobil.drop(columns="Unnamed: 0", inplace=True)
display(mobil)

,country,region,date,retail_and_recreation,grocery_and_pharmacy,parks,transit_stations,workplaces,residential
0,United Arab Emirates,Total,2020-02-15,0.0,4.0,5.0,0.0,2.0,1.0
1,United Arab Emirates,Total,2020-02-16,1.0,4.0,4.0,1.0,2.0,1.0
2,United Arab Emirates,Total,2020-02-17,-1.0,1.0,5.0,1.0,2.0,1.0
3,United Arab Emirates,Total,2020-02-18,-2.0,1.0,5.0,0.0,2.0,1.0
4,United Arab Emirates,Total,2020-02-19,-2.0,0.0,4.0,-1.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...
310337,Zimbabwe,Midlands Province,2020-07-21,NaN,NaN,NaN,NaN,-4.0,NaN
310338,Zimbabwe,Midlands Province,2020-07-22,NaN,NaN,NaN,NaN,-11.0,NaN
310339,Zimbabwe,Midlands Province,2020-07-23,NaN,NaN,NaN,NaN,-11.0,NaN
310340,Zimbabwe,Midlands Province,2020-07-24,NaN,NaN,NaN,NaN,-11.0,NaN
310341,Zimbabwe,Midlands Province,2020-07-25,NaN,NaN,NaN,NaN,13.0,NaN

In [35]:
# discard countries in mobility df that aren't present in the previous df
mobilCountry_list = list(mobil['country'].unique())
mobilCountry_list

for country in mobilCountry_list:
    if country not in countries:
        lessCountries_df = mobil[(mobil['country'] != country)]

display(lessCountries_df)
len(list(lessCountries_df['country'].unique()))

,country,region,date,retail_and_recreation,grocery_and_pharmacy,parks,transit_stations,workplaces,residential
0,United Arab Emirates,Total,2020-02-15,0.0,4.0,5.0,0.0,2.0,1.0
1,United Arab Emirates,Total,2020-02-16,1.0,4.0,4.0,1.0,2.0,1.0
2,United Arab Emirates,Total,2020-02-17,-1.0,1.0,5.0,1.0,2.0,1.0
3,United Arab Emirates,Total,2020-02-18,-2.0,1.0,5.0,0.0,2.0,1.0
4,United Arab Emirates,Total,2020-02-19,-2.0,0.0,4.0,-1.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...
310337,Zimbabwe,Midlands Province,2020-07-21,NaN,NaN,NaN,NaN,-4.0,NaN
310338,Zimbabwe,Midlands Province,2020-07-22,NaN,NaN,NaN,NaN,-11.0,NaN
310339,Zimbabwe,Midlands Province,2020-07-23,NaN,NaN,NaN,NaN,-11.0,NaN
310340,Zimbabwe,Midlands Province,2020-07-24,NaN,NaN,NaN,NaN,-11.0,NaN
310341,Zimbabwe,Midlands Province,2020-07-25,NaN,NaN,NaN,NaN,13.0,NaN

134

In [36]:
# drop rows if date is BEFORE date of min. gov response

minDate_df = mergeEcon[['location','minDate']]
minDate_df.rename(columns={'location':'country'}, inplace=True)
minDate_df

# determine date 3 mnths AFTER date of min. gov response
minDate_df['3mnth'] = minDate_df['minDate'] + timedelta(days = 90)
minDate_df

/Users/patricialan/opt/anaconda3/envs/PythonData/lib/python3.8/site-packages/pandas/core/frame.py:4125: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(
<ipython-input-36-bdbe81040b21>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  minDate_df['3mnth'] = minDate_df['minDate'] + timedelta(days = 90)

         country    minDate      3mnth
0    Afghanistan 2020-03-01 2020-05-30
1        Albania 2020-03-09 2020-06-07
2        Algeria 2020-03-12 2020-06-10
3         Angola 2020-03-24 2020-06-22
4      Argentina 2020-03-04 2020-06-02
..           ...        ...        ...
159    Venezuela 2020-03-15 2020-06-13
160      Vietnam 2020-01-29 2020-04-28
161        Yemen 2020-04-10 2020-07-09
162       Zambia 2020-03-19 2020-06-17
163     Zimbabwe 2020-03-21 2020-06-19

[164 rows x 3 columns]

In [37]:
# merge "3-MO-later" date with rest of mobility df
mobilDate_df = lessCountries_df.merge(minDate_df, on='country', how='left')
mobilDate_df['date'] = pd.to_datetime(mobilDate_df['date'])

# ensure merged correctly with proper dtypes
display(mobilDate_df)
mobilDate_df.dtypes

,country,region,date,retail_and_recreation,grocery_and_pharmacy,parks,transit_stations,workplaces,residential,minDate,3mnth
0,United Arab Emirates,Total,2020-02-15,0.0,4.0,5.0,0.0,2.0,1.0,2020-03-01,2020-05-30
1,United Arab Emirates,Total,2020-02-16,1.0,4.0,4.0,1.0,2.0,1.0,2020-03-01,2020-05-30
2,United Arab Emirates,Total,2020-02-17,-1.0,1.0,5.0,1.0,2.0,1.0,2020-03-01,2020-05-30
3,United Arab Emirates,Total,2020-02-18,-2.0,1.0,5.0,0.0,2.0,1.0,2020-03-01,2020-05-30
4,United Arab Emirates,Total,2020-02-19,-2.0,0.0,4.0,-1.0,2.0,1.0,2020-03-01,2020-05-30
...,...,...,...,...,...,...,...,...,...,...,...
310175,Zimbabwe,Midlands Province,2020-07-21,NaN,NaN,NaN,NaN,-4.0,NaN,2020-03-21,2020-06-19
310176,Zimbabwe,Midlands Province,2020-07-22,NaN,NaN,NaN,NaN,-11.0,NaN,2020-03-21,2020-06-19
310177,Zimbabwe,Midlands Province,2020-07-23,NaN,NaN,NaN,NaN,-11.0,NaN,2020-03-21,2020-06-19
310178,Zimbabwe,Midlands Province,2020-07-24,NaN,NaN,NaN,NaN,-11.0,NaN,2020-03-21,2020-06-19
310179,Zimbabwe,Midlands Province,2020-07-25,NaN,NaN,NaN,NaN,13.0,NaN,2020-03-21,2020-06-19

country                          object
region                           object
date                     datetime64[ns]
retail_and_recreation           float64
grocery_and_pharmacy            float64
parks                           float64
transit_stations                float64
workplaces                      float64
residential                     float64
minDate                  datetime64[ns]
3mnth                    datetime64[ns]
dtype: object

In [38]:
# remove dates AFTER the 3 MO date

newMobilCountry_list = list(mobilDate_df['country'].unique())
len(newMobilCountry_list)

countryLoc_list = []

for i in range(0,134):
    country = newMobilCountry_list[i]
    countryLoc = mobilDate_df.loc[mobilDate_df['country'] == country]
    datesAfterGR_df = countryLoc[(countryLoc['date'] > countryLoc['minDate'])]
    dates3mnthAfterMinDate_df = datesAfterGR_df[datesAfterGR_df['date'] <= datesAfterGR_df['3mnth']]
    
    countryLoc_list.append(dates3mnthAfterMinDate_df)
    mobil3mnth_df = pd.concat(countryLoc_list)

# check the df
display(mobil3mnth_df)

# save df
mobil3mnth_df.to_csv("mobil_3mnth.csv", index=False)

,country,region,date,retail_and_recreation,grocery_and_pharmacy,parks,transit_stations,workplaces,residential,minDate,3mnth
16,United Arab Emirates,Total,2020-03-02,0.0,7.0,1.0,-2.0,4.0,1.0,2020-03-01,2020-05-30
17,United Arab Emirates,Total,2020-03-03,0.0,6.0,0.0,-5.0,4.0,1.0,2020-03-01,2020-05-30
18,United Arab Emirates,Total,2020-03-04,-1.0,7.0,-2.0,-5.0,3.0,2.0,2020-03-01,2020-05-30
19,United Arab Emirates,Total,2020-03-05,-3.0,6.0,-2.0,-5.0,3.0,2.0,2020-03-01,2020-05-30
20,United Arab Emirates,Total,2020-03-06,-7.0,5.0,-8.0,-9.0,0.0,3.0,2020-03-01,2020-05-30
...,...,...,...,...,...,...,...,...,...,...,...
310139,Zimbabwe,Midlands Province,2020-06-15,NaN,NaN,NaN,NaN,-5.0,NaN,2020-03-21,2020-06-19
310140,Zimbabwe,Midlands Province,2020-06-16,NaN,NaN,NaN,NaN,-2.0,NaN,2020-03-21,2020-06-19
310141,Zimbabwe,Midlands Province,2020-06-17,NaN,NaN,NaN,NaN,-15.0,NaN,2020-03-21,2020-06-19
310142,Zimbabwe,Midlands Province,2020-06-18,NaN,NaN,NaN,NaN,-9.0,NaN,2020-03-21,2020-06-19
310143,Zimbabwe,Midlands Province,2020-06-19,NaN,NaN,NaN,NaN,-2.0,NaN,2020-03-21,2020-06-19

In [39]:
# get avg. change in mobility outdoors and indoors 
avgMobil_df = mobil3mnth_df.groupby(['country']).mean()

# check df
display(avgMobil_df)
avgMobil_df.dtypes

,retail_and_recreation,grocery_and_pharmacy,parks,transit_stations,workplaces,residential
country,,,,,,
Afghanistan,-29.666667,-13.307692,-10.076923,-31.410256,-21.500000,9.333333
Angola,-39.761905,-21.725581,-34.577778,-54.162562,-20.486726,20.988889
Argentina,-65.059556,-28.504444,-73.733333,-60.525193,-31.805778,18.844000
Aruba,-53.244444,-22.488889,-36.044444,-59.988889,-47.900000,22.211268
Australia,-18.239683,0.884127,-14.788889,-25.447619,-10.907937,7.853035
...,...,...,...,...,...,...
Venezuela,-54.411111,-33.966667,-47.477778,-55.400000,-38.755556,17.955556
Vietnam,-27.892948,-20.098515,-20.971131,-32.089387,-5.979096,9.433304
Yemen,-8.622222,1.633333,-10.466667,-9.344444,-9.100000,6.155556
Zambia,-12.600000,-4.111111,-1.488889,-16.433333,-7.466667,11.311111
Zimbabwe,-43.195730,-27.116732,-38.723757,-58.448529,-28.962585,28.821990

retail_and_recreation    float64
grocery_and_pharmacy     float64
parks                    float64
transit_stations         float64
workplaces               float64
residential              float64
dtype: object

In [40]:
# get the avg. of all "outdoors" mobility columns
avgMobil_df['avgOutdoorMobil'] = (avgMobil_df['retail_and_recreation'] + avgMobil_df['grocery_and_pharmacy'] + avgMobil_df['parks'] + avgMobil_df['transit_stations'] + avgMobil_df['workplaces'])/5

avgMobil_df = avgMobil_df.reset_index()
avgMobil_df.rename(columns={"country":"location"}, inplace=True)
avgMobil_df

,location,retail_and_recreation,grocery_and_pharmacy,parks,transit_stations,workplaces,residential,avgOutdoorMobil
0,Afghanistan,-29.666667,-13.307692,-10.076923,-31.410256,-21.500000,9.333333,-21.192308
1,Angola,-39.761905,-21.725581,-34.577778,-54.162562,-20.486726,20.988889,-34.142910
2,Argentina,-65.059556,-28.504444,-73.733333,-60.525193,-31.805778,18.844000,-51.925661
3,Aruba,-53.244444,-22.488889,-36.044444,-59.988889,-47.900000,22.211268,-43.933333
4,Australia,-18.239683,0.884127,-14.788889,-25.447619,-10.907937,7.853035,-13.700000
...,...,...,...,...,...,...,...,...
119,Venezuela,-54.411111,-33.966667,-47.477778,-55.400000,-38.755556,17.955556,-46.002222
120,Vietnam,-27.892948,-20.098515,-20.971131,-32.089387,-5.979096,9.433304,-21.406215
121,Yemen,-8.622222,1.633333,-10.466667,-9.344444,-9.100000,6.155556,-7.180000
122,Zambia,-12.600000,-4.111111,-1.488889,-16.433333,-7.466667,11.311111,-8.420000
123,Zimbabwe,-43.195730,-27.116732,-38.723757,-58.448529,-28.962585,28.821990,-39.289466

In [41]:
# merge mobility df with previous df
merge = mergeEcon.merge(avgMobil_df, on='location', how='left')

# check merged df
display(merge)
merge.columns.to_list()

,location,primary_key_reaction,iso_code,minDate,maxDate,maxValue,changeGovResp,ramp_up_duration,population,population_density,...,StringencyIndex_updated,ContainmentHealthIndex_updated,EconomicSupportIndex_updated,retail_and_recreation,grocery_and_pharmacy,parks,transit_stations,workplaces,residential,avgOutdoorMobil
0,Afghanistan,AFG2020-08-31,AFG,2020-03-01,2020-04-12,64.74,50.74,42 days,38928341.0,54.422,...,77.056601,71.595294,0.000000,-29.666667,-13.307692,-10.076923,-31.410256,-21.500000,9.333333,-21.192308
1,Albania,ALB2020-08-31,ALB,2020-03-09,2020-05-26,81.41,67.41,78 days,2877800.0,104.871,...,71.082157,69.281699,64.133987,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Algeria,DZA2020-08-31,DZA,2020-03-12,2020-08-08,78.85,64.85,149 days,43851043.0,17.348,...,77.349804,70.179869,44.117647,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Angola,AGO2020-08-31,AGO,2020-03-24,2020-04-09,75.64,61.64,16 days,32866268.0,23.890,...,79.376863,71.983987,39.869281,-39.761905,-21.725581,-34.577778,-54.162562,-20.486726,20.988889,-34.142910
4,Argentina,ARG2020-08-31,ARG,2020-03-04,2020-03-25,91.03,77.03,21 days,45195777.0,16.177,...,91.496536,87.041569,75.000000,-65.059556,-28.504444,-73.733333,-60.525193,-31.805778,18.844000,-51.925661
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,Venezuela,VEN2020-08-31,VEN,2020-03-15,2020-06-22,75.64,61.64,99 days,28435943.0,36.253,...,84.127516,76.455817,50.000000,-54.411111,-33.966667,-47.477778,-55.400000,-38.755556,17.955556,-46.002222
160,Vietnam,VNM2020-08-31,VNM,2020-01-29,2020-04-09,85.90,71.90,71 days,97338583.0,308.127,...,68.959869,73.456863,31.535948,-27.892948,-20.098515,-20.971131,-32.089387,-5.979096,9.433304,-21.406215
161,Yemen,YEM2020-08-31,YEM,2020-04-10,2020-05-01,40.38,26.38,21 days,29825968.0,53.508,...,46.230000,37.827153,0.000000,-8.622222,1.633333,-10.466667,-9.344444,-9.100000,6.155556,-7.180000
162,Zambia,ZMB2020-08-31,ZMB,2020-03-19,2020-05-02,63.14,49.14,44 days,18383956.0,22.995,...,50.076405,53.093987,25.000000,-12.600000,-4.111111,-1.488889,-16.433333,-7.466667,11.311111,-8.420000
163,Zimbabwe,ZWE2020-08-31,ZWE,2020-03-21,2020-04-09,71.15,57.15,19 days,14862927.0,42.729,...,81.166471,73.826405,23.856209,-43.195730,-27.116732,-38.723757,-58.448529,-28.962585,28.821990,-39.289466

['location',
 'primary_key_reaction',
 'iso_code',
 'minDate',
 'maxDate',
 'maxValue',
 'changeGovResp',
 'ramp_up_duration',
 'population',
 'population_density',
 'median_age',
 'newCases_startDate',
 'CaseVsResp_Interval',
 'AvgMaxGovResp_StartApr1',
 'MaxNewCases_date',
 'MaxNewCases_value',
 'StartToMaxNewCases_Interval',
 'MaxNewDeaths_date',
 'MaxNewDeaths_value',
 'MaxNewCasesToMaxNewDeaths_Interval',
 'FirstNewCaseToMaxNewDeaths',
 '3mth_date',
 'newCases_3mnth',
 'totCases_3mnth',
 'newDeaths_3mnth',
 'totDeaths_3mnth',
 'gdp_per_capita',
 'StringencyIndex_updated',
 'ContainmentHealthIndex_updated',
 'EconomicSupportIndex_updated',
 'retail_and_recreation',
 'grocery_and_pharmacy',
 'parks',
 'transit_stations',
 'workplaces',
 'residential',
 'avgOutdoorMobil']

In [42]:
# save to csv
merge.to_csv("govRespOutcome_noC1H5.csv", index=False)