In [1]:
import numpy as np
import pandas as pd
import re

In [2]:
path_GR = "../Resources/raw/OxCGRT_latest(Aug31,2020).csv"   # Government Response
path_CD = "../Resources/raw/owid-covid-data(Aug31,2020).csv"   # COVID Data

In [3]:
data_GR = pd.read_csv(path_GR)    #Government Response
data_CD = pd.read_csv(path_CD)

C:\Users\muzzn\anaconda3\envs\PythonData\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (2,3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
data_GR.columns

Index(['CountryName', 'CountryCode', 'RegionName', 'RegionCode', 'Date',
       'C1_School closing', 'C1_Flag', 'C2_Workplace closing', 'C2_Flag',
       'C3_Cancel public events', 'C3_Flag', 'C4_Restrictions on gatherings',
       'C4_Flag', 'C5_Close public transport', 'C5_Flag',
       'C6_Stay at home requirements', 'C6_Flag',
       'C7_Restrictions on internal movement', 'C7_Flag',
       'C8_International travel controls', 'E1_Income support', 'E1_Flag',
       'E2_Debt/contract relief', 'E3_Fiscal measures',
       'E4_International support', 'H1_Public information campaigns',
       'H1_Flag', 'H2_Testing policy', 'H3_Contact tracing',
       'H4_Emergency investment in healthcare', 'H5_Investment in vaccines',
       'M1_Wildcard', 'ConfirmedCases', 'ConfirmedDeaths', 'StringencyIndex',
       'StringencyIndexForDisplay', 'StringencyLegacyIndex',
       'StringencyLegacyIndexForDisplay', 'GovernmentResponseIndex',
       'GovernmentResponseIndexForDisplay', 'ContainmentHealthIndex',
       'ContainmentHealthIndexForDisplay', 'EconomicSupportIndex',
       'EconomicSupportIndexForDisplay'],
      dtype='object')

In [7]:
df_GR = data_GR[['Date','CountryCode']]
HealthEco_columns = [ x for x in data_GR if re.search("H\d|E\d",x)]

for x in HealthEco_columns:
    df_GR[x] = data_GR[x]
    
df_GR

C:\Users\muzzn\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

,Date,CountryCode,E1_Income support,E1_Flag,E2_Debt/contract relief,E3_Fiscal measures,E4_International support,H1_Public information campaigns,H1_Flag,H2_Testing policy,H3_Contact tracing,H4_Emergency investment in healthcare,H5_Investment in vaccines
0,20200101,ABW,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
1,20200102,ABW,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
2,20200103,ABW,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
3,20200104,ABW,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
4,20200105,ABW,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58799,20200827,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58800,20200828,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58801,20200829,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58802,20200830,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58803,20200831,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df_GR.isnull().sum()

Date                                         0
CountryCode                                  0
E1_Income support                         2793
E1_Flag                                  30792
E2_Debt/contract relief                   3222
E3_Fiscal measures                       12399
E4_International support                 12205
H1_Public information campaigns           2299
H1_Flag                                  13060
H2_Testing policy                         2643
H3_Contact tracing                        2671
H4_Emergency investment in healthcare    12890
H5_Investment in vaccines                12487
dtype: int64

In [9]:
for x in df_GR.columns:
    if re.search("H\d|E\d",x):
        print(df_GR[x].value_counts())

0.0    27999
2.0    16153
1.0    11859
Name: E1_Income support, dtype: int64
0.0    16001
1.0    12011
Name: E1_Flag, dtype: int64
0.0    25627
2.0    15632
1.0    14323
Name: E2_Debt/contract relief, dtype: int64
0.000000e+00    45827
3.000000e+00       11
1.000000e+07        7
2.000000e+08        5
1.000000e+09        4
                ...
1.264000e+06        1
2.100000e+09        1
1.465400e+10        1
2.290000e+08        1
1.269000e+09        1
Name: E3_Fiscal measures, Length: 516, dtype: int64
0.000000e+00    46519
5.000000e+06        5
1.000000e+07        3
1.000000e+06        2
3.000000e+07        2
                ...
3.000000e+00        1
5.000000e+01        1
1.740000e+09        1
2.205070e+05        1
6.011700e+06        1
Name: E4_International support, Length: 70, dtype: int64
2.0    41015
0.0    10761
1.0     4729
Name: H1_Public information campaigns, dtype: int64
1.0    45319
0.0      425
Name: H1_Flag, dtype: int64
1.0    21618
2.0    14442
0.0    11927
3.0     8174
Name: H2_Testing policy, dtype: int64
2.0    21005
1.0    19938
0.0    15190
Name: H3_Contact tracing, dtype: int64
0.000000e+00    45499
3.500000e+01       39
5.620000e+02       20
2.070000e+01       10
1.000000e+06        7
                ...
4.000000e+08        1
1.575250e+05        1
8.072180e+07        1
1.560250e+09        1
3.546507e+07        1
Name: H4_Emergency investment in healthcare, Length: 309, dtype: int64
0.000000e+00    46187
1.000000e+00       43
1.910000e+02       21
1.000000e+07        3
2.545911e+08        2
                ...
1.741000e+08        1
3.242505e+06        1
1.963391e+07        1
1.390000e+09        1
5.953246e+06        1
Name: H5_Investment in vaccines, Length: 65, dtype: int64

In [10]:
df_GR = df_GR.fillna(0)

In [11]:
df_CD_1 = data_CD[["date","iso_code","total_cases","total_deaths"]]
df_CD_2 = data_CD[["date","iso_code","new_cases","new_deaths"]]
df_CD_2 = df_CD_2.fillna(0)

In [12]:
df_CD = df_CD_1.merge(df_CD_2,on=["date","iso_code"])

In [13]:
df_CD.head()

         date iso_code  total_cases  total_deaths  new_cases  new_deaths
0  2020-03-13      ABW          2.0           0.0        2.0         0.0
1  2020-03-19      ABW          NaN           NaN        0.0         0.0
2  2020-03-20      ABW          4.0           0.0        2.0         0.0
3  2020-03-21      ABW          NaN           NaN        0.0         0.0
4  2020-03-22      ABW          NaN           NaN        0.0         0.0

In [14]:
codes = df_CD["iso_code"].unique()

iso_dfs = []

total_cases_col = 2
tota_deaths_col = 3

for code in codes:
    iso_df = df_CD[df_CD["iso_code"] == code]
    if np.isnan(iso_df.iloc[0,total_cases_col]):
        iso_df.iloc[0,total_cases_col] = 0
    if np.isnan(iso_df.iloc[0,tota_deaths_col]):
        iso_df.iloc[0,tota_deaths_col] = 0
    
    iso_df = iso_df.fillna(method='ffill')
    
    iso_dfs.append(iso_df)

df_CD = pd.DataFrame()

for iso_df in iso_dfs:
    df_CD = df_CD.append(iso_df)
    
df_CD.isnull().sum()

C:\Users\muzzn\anaconda3\envs\PythonData\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

date            0
iso_code        0
total_cases     0
total_deaths    0
new_cases       0
new_deaths      0
dtype: int64

In [15]:
df_CD

             date  iso_code  total_cases  total_deaths  new_cases  new_deaths
0      2020-03-13       ABW          2.0           0.0        2.0         0.0
1      2020-03-19       ABW          2.0           0.0        0.0         0.0
2      2020-03-20       ABW          4.0           0.0        2.0         0.0
3      2020-03-21       ABW          4.0           0.0        0.0         0.0
4      2020-03-22       ABW          4.0           0.0        0.0         0.0
...           ...       ...          ...           ...        ...         ...
40498  2020-08-27  OWID_WRL   24201449.0      825936.0   276699.0      6297.0
40499  2020-08-28  OWID_WRL   24484672.0      832011.0   283223.0      6075.0
40500  2020-08-29  OWID_WRL   24761119.0      837466.0   276447.0      5455.0
40501  2020-08-30  OWID_WRL   25029850.0      843154.0   268731.0      5688.0
40502  2020-08-31  OWID_WRL   25251334.0      846841.0   221484.0      3687.0

[40503 rows x 6 columns]

In [16]:
df_GR.columns

Index(['Date', 'CountryCode', 'E1_Income support', 'E1_Flag',
       'E2_Debt/contract relief', 'E3_Fiscal measures',
       'E4_International support', 'H1_Public information campaigns',
       'H1_Flag', 'H2_Testing policy', 'H3_Contact tracing',
       'H4_Emergency investment in healthcare', 'H5_Investment in vaccines'],
      dtype='object')

In [17]:
df_CD.columns

Index(['date', 'iso_code', 'total_cases', 'total_deaths', 'new_cases',
       'new_deaths'],
      dtype='object')

In [18]:
df_GR = df_GR.rename(columns={"Date":"date","CountryCode":"iso_code"})

In [19]:
def formatDate(dt):
    d_str = str(dt)
    year = d_str[0:4]
#     print(year)
    month = d_str[4:6]
#     print(month)
    day = d_str[6:8]
#     print(day)
    dt_str = year + "-" + month + "-" + day
    
    return dt_str

In [21]:
type(df_GR["date"][0])

numpy.int64

In [22]:
formatDate(df_GR["date"][0])

'2020-01-01'

In [23]:
df_GR["date"] = df_GR["date"].apply(lambda x:formatDate(x))

In [24]:
df_GR.head()

,date,iso_code,E1_Income support,E1_Flag,E2_Debt/contract relief,E3_Fiscal measures,E4_International support,H1_Public information campaigns,H1_Flag,H2_Testing policy,H3_Contact tracing,H4_Emergency investment in healthcare,H5_Investment in vaccines
0,2020-01-01,ABW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2020-01-02,ABW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2020-01-03,ABW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2020-01-04,ABW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2020-01-05,ABW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
df_CD.head()

         date iso_code  total_cases  total_deaths  new_cases  new_deaths
0  2020-03-13      ABW          2.0           0.0        2.0         0.0
1  2020-03-19      ABW          2.0           0.0        0.0         0.0
2  2020-03-20      ABW          4.0           0.0        2.0         0.0
3  2020-03-21      ABW          4.0           0.0        0.0         0.0
4  2020-03-22      ABW          4.0           0.0        0.0         0.0

In [26]:
final_df = df_GR.merge(df_CD,on=["date","iso_code"])
final_df

,date,iso_code,E1_Income support,E1_Flag,E2_Debt/contract relief,E3_Fiscal measures,E4_International support,H1_Public information campaigns,H1_Flag,H2_Testing policy,H3_Contact tracing,H4_Emergency investment in healthcare,H5_Investment in vaccines,total_cases,total_deaths,new_cases,new_deaths
0,2020-03-13,ABW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0
1,2020-03-19,ABW,0.0,0.0,0.0,0.0,0.0,2.0,1.0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0
2,2020-03-20,ABW,0.0,0.0,0.0,0.0,0.0,2.0,1.0,1.0,1.0,0.0,0.0,4.0,0.0,2.0,0.0
3,2020-03-21,ABW,0.0,0.0,0.0,0.0,0.0,2.0,1.0,1.0,1.0,0.0,0.0,4.0,0.0,0.0,0.0
4,2020-03-22,ABW,0.0,0.0,0.0,0.0,0.0,2.0,1.0,1.0,1.0,0.0,0.0,4.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48523,2020-08-27,ZWE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6251.0,179.0,55.0,13.0
48524,2020-08-28,ZWE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6292.0,189.0,41.0,10.0
48525,2020-08-29,ZWE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6388.0,195.0,96.0,6.0
48526,2020-08-30,ZWE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6406.0,196.0,18.0,1.0
48527,2020-08-31,ZWE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6412.0,196.0,6.0,0.0

In [27]:
final_df.to_csv("../Resources/HealthEcoColumns.csv")

In [28]:
!pwd

The system cannot find the path specified.
'pwd' is not recognized as an internal or external command,
operable program or batch file.